// flow-typed signature: 0b9526515af9938f790ecae6de206b32
// flow-typed version: <<STUB>>/apollo-link-ws_v^0.3.4/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-ws/dist/src/webSocketLink' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/dist/tests/tests' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/dist/tests/webSocketLink' {
  declare module.exports: any;
}

declare module 'apollo-link-ws/lib/webSocketLink' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-ws/dist/src/webSocketLink.js' {
  declare module.exports: $Exports<'apollo-link-ws/dist/src/webSocketLink'>;
}
declare module 'apollo-link-ws/dist/tests/tests.js' {
  declare module.exports: $Exports<'apollo-link-ws/dist/tests/tests'>;
}
declare module 'apollo-link-ws/dist/tests/webSocketLink.js' {
  declare module.exports: $Exports<'apollo-link-ws/dist/tests/webSocketLink'>;
}
declare module 'apollo-link-ws/lib/webSocketLink.js' {
  declare module.exports: $Exports<'apollo-link-ws/lib/webSocketLink'>;
}
