// flow-typed signature: 8c17610ff47905061ba73c3236688481
// flow-typed version: <<STUB>>/apollo-logger_v0.0.5/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-logger/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-logger/lib/index.js' {
  declare module.exports: $Exports<'apollo-logger/lib/index'>;
}
