// flow-typed signature: 60c397b3d8bdb3219f7813cb75dfb257
// flow-typed version: <<STUB>>/apollo-fetch_v^0.6.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-fetch/dist/apollo-fetch' {
  declare module.exports: any;
}

declare module 'apollo-fetch/dist/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-fetch/dist/index' {
  declare module.exports: any;
}

declare module 'apollo-fetch/dist/types' {
  declare module.exports: any;
}

declare module 'apollo-fetch/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-fetch/dist/apollo-fetch.js' {
  declare module.exports: $Exports<'apollo-fetch/dist/apollo-fetch'>;
}
declare module 'apollo-fetch/dist/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-fetch/dist/bundle.umd'>;
}
declare module 'apollo-fetch/dist/index.js' {
  declare module.exports: $Exports<'apollo-fetch/dist/index'>;
}
declare module 'apollo-fetch/dist/types.js' {
  declare module.exports: $Exports<'apollo-fetch/dist/types'>;
}
declare module 'apollo-fetch/rollup.config.js' {
  declare module.exports: $Exports<'apollo-fetch/rollup.config'>;
}
