// flow-typed signature: 6cee3674187c6326d64b5ed692aa03af
// flow-typed version: <<STUB>>/apollo-server-express_v^1.1.6/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server-express/dist/connectApollo' {
  declare module.exports: any;
}

declare module 'apollo-server-express/dist/expressApollo' {
  declare module.exports: any;
}

declare module 'apollo-server-express/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server-express/dist/connectApollo.js' {
  declare module.exports: $Exports<'apollo-server-express/dist/connectApollo'>;
}
declare module 'apollo-server-express/dist/expressApollo.js' {
  declare module.exports: $Exports<'apollo-server-express/dist/expressApollo'>;
}
declare module 'apollo-server-express/dist/index.js' {
  declare module.exports: $Exports<'apollo-server-express/dist/index'>;
}
