// flow-typed signature: 8fafb65d187606a9651eda828db1af1d
// flow-typed version: <<STUB>>/apollo-cache-inmemory_vhttps://github.com/vlasenko/apollo-client/raw/master/packages/apollo-cache-inmemory/apollo-cache-inmemory-0.2.0-beta.1.tar/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-cache-inmemory'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-cache-inmemory' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-cache-inmemory/lib/fragmentMatcher' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/fragmentMatcherIntrospectionQuery' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/inMemoryCache' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/readFromStore' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/types' {
  declare module.exports: any;
}

declare module 'apollo-cache-inmemory/lib/writeToStore' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-cache-inmemory/lib/fragmentMatcher.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/fragmentMatcher'>;
}
declare module 'apollo-cache-inmemory/lib/fragmentMatcherIntrospectionQuery.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/fragmentMatcherIntrospectionQuery'>;
}
declare module 'apollo-cache-inmemory/lib/index.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/index'>;
}
declare module 'apollo-cache-inmemory/lib/inMemoryCache.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/inMemoryCache'>;
}
declare module 'apollo-cache-inmemory/lib/readFromStore.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/readFromStore'>;
}
declare module 'apollo-cache-inmemory/lib/types.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/types'>;
}
declare module 'apollo-cache-inmemory/lib/writeToStore.js' {
  declare module.exports: $Exports<'apollo-cache-inmemory/lib/writeToStore'>;
}
