// flow-typed signature: 157703c999ec48db4735b7ff82b6f730
// flow-typed version: <<STUB>>/apollo-logger_v0.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-logger/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-logger/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-logger/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-logger/lib/bundle.umd'>;
}
declare module 'apollo-logger/lib/index.js' {
  declare module.exports: $Exports<'apollo-logger/lib/index'>;
}
