// flow-typed signature: 3f7f91b8ff119df81a2b6e7880910ce8
// flow-typed version: <<STUB>>/bootstrap_v4.0.0-beta/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bootstrap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bootstrap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bootstrap/build/change-version' {
  declare module.exports: any;
}

declare module 'bootstrap/build/postcss.config' {
  declare module.exports: any;
}

declare module 'bootstrap/build/stamp' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap' {
  declare module.exports: any;
}

declare module 'bootstrap/dist/js/bootstrap.min' {
  declare module.exports: any;
}

declare module 'bootstrap/Gruntfile' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/button' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/js/dist/util' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/button' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/js/src/util' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/alert' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/button' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/carousel' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/collapse' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/dropdown' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/modal' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/popover' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/scrollspy' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/tab' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/unit/tooltip' {
  declare module.exports: any;
}

declare module 'bootstrap/js/tests/vendor/qunit' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bootstrap/build/change-version.js' {
  declare module.exports: $Exports<'bootstrap/build/change-version'>;
}
declare module 'bootstrap/build/postcss.config.js' {
  declare module.exports: $Exports<'bootstrap/build/postcss.config'>;
}
declare module 'bootstrap/build/stamp.js' {
  declare module.exports: $Exports<'bootstrap/build/stamp'>;
}
declare module 'bootstrap/dist/js/bootstrap.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap'>;
}
declare module 'bootstrap/dist/js/bootstrap.min.js' {
  declare module.exports: $Exports<'bootstrap/dist/js/bootstrap.min'>;
}
declare module 'bootstrap/Gruntfile.js' {
  declare module.exports: $Exports<'bootstrap/Gruntfile'>;
}
declare module 'bootstrap/js/dist/alert.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/alert'>;
}
declare module 'bootstrap/js/dist/button.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/button'>;
}
declare module 'bootstrap/js/dist/carousel.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/carousel'>;
}
declare module 'bootstrap/js/dist/collapse.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/collapse'>;
}
declare module 'bootstrap/js/dist/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/dropdown'>;
}
declare module 'bootstrap/js/dist/modal.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/modal'>;
}
declare module 'bootstrap/js/dist/popover.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/popover'>;
}
declare module 'bootstrap/js/dist/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/scrollspy'>;
}
declare module 'bootstrap/js/dist/tab.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/tab'>;
}
declare module 'bootstrap/js/dist/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/tooltip'>;
}
declare module 'bootstrap/js/dist/util.js' {
  declare module.exports: $Exports<'bootstrap/js/dist/util'>;
}
declare module 'bootstrap/js/src/alert.js' {
  declare module.exports: $Exports<'bootstrap/js/src/alert'>;
}
declare module 'bootstrap/js/src/button.js' {
  declare module.exports: $Exports<'bootstrap/js/src/button'>;
}
declare module 'bootstrap/js/src/carousel.js' {
  declare module.exports: $Exports<'bootstrap/js/src/carousel'>;
}
declare module 'bootstrap/js/src/collapse.js' {
  declare module.exports: $Exports<'bootstrap/js/src/collapse'>;
}
declare module 'bootstrap/js/src/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/js/src/dropdown'>;
}
declare module 'bootstrap/js/src/modal.js' {
  declare module.exports: $Exports<'bootstrap/js/src/modal'>;
}
declare module 'bootstrap/js/src/popover.js' {
  declare module.exports: $Exports<'bootstrap/js/src/popover'>;
}
declare module 'bootstrap/js/src/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/js/src/scrollspy'>;
}
declare module 'bootstrap/js/src/tab.js' {
  declare module.exports: $Exports<'bootstrap/js/src/tab'>;
}
declare module 'bootstrap/js/src/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/js/src/tooltip'>;
}
declare module 'bootstrap/js/src/util.js' {
  declare module.exports: $Exports<'bootstrap/js/src/util'>;
}
declare module 'bootstrap/js/tests/unit/alert.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/alert'>;
}
declare module 'bootstrap/js/tests/unit/button.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/button'>;
}
declare module 'bootstrap/js/tests/unit/carousel.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/carousel'>;
}
declare module 'bootstrap/js/tests/unit/collapse.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/collapse'>;
}
declare module 'bootstrap/js/tests/unit/dropdown.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/dropdown'>;
}
declare module 'bootstrap/js/tests/unit/modal.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/modal'>;
}
declare module 'bootstrap/js/tests/unit/popover.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/popover'>;
}
declare module 'bootstrap/js/tests/unit/scrollspy.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/scrollspy'>;
}
declare module 'bootstrap/js/tests/unit/tab.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/tab'>;
}
declare module 'bootstrap/js/tests/unit/tooltip.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/unit/tooltip'>;
}
declare module 'bootstrap/js/tests/vendor/qunit.js' {
  declare module.exports: $Exports<'bootstrap/js/tests/vendor/qunit'>;
}
