// flow-typed signature: 4cf2beff925d30c5aba4212b27240c15
// flow-typed version: <<STUB>>/caporal_v^0.7.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caporal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caporal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'caporal/docs/bootstrap.min' {
  declare module.exports: any;
}

declare module 'caporal/docs/jquery.min' {
  declare module.exports: any;
}

declare module 'caporal/lib/argument' {
  declare module.exports: any;
}

declare module 'caporal/lib/autocomplete' {
  declare module.exports: any;
}

declare module 'caporal/lib/colorful' {
  declare module.exports: any;
}

declare module 'caporal/lib/command' {
  declare module.exports: any;
}

declare module 'caporal/lib/constants' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/base-error' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/invalid-argument-value' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/invalid-option-value' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/missing-option' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/no-action-error' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/option-syntax-error' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/unknown-option' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/validation-error' {
  declare module.exports: any;
}

declare module 'caporal/lib/error/wrong-num-of-arg' {
  declare module.exports: any;
}

declare module 'caporal/lib/help' {
  declare module.exports: any;
}

declare module 'caporal/lib/logger' {
  declare module.exports: any;
}

declare module 'caporal/lib/option' {
  declare module.exports: any;
}

declare module 'caporal/lib/program' {
  declare module.exports: any;
}

declare module 'caporal/lib/suggest' {
  declare module.exports: any;
}

declare module 'caporal/lib/utils' {
  declare module.exports: any;
}

declare module 'caporal/lib/validator' {
  declare module.exports: any;
}

// Filename aliases
declare module 'caporal/docs/bootstrap.min.js' {
  declare module.exports: $Exports<'caporal/docs/bootstrap.min'>;
}
declare module 'caporal/docs/jquery.min.js' {
  declare module.exports: $Exports<'caporal/docs/jquery.min'>;
}
declare module 'caporal/index' {
  declare module.exports: $Exports<'caporal'>;
}
declare module 'caporal/index.js' {
  declare module.exports: $Exports<'caporal'>;
}
declare module 'caporal/lib/argument.js' {
  declare module.exports: $Exports<'caporal/lib/argument'>;
}
declare module 'caporal/lib/autocomplete.js' {
  declare module.exports: $Exports<'caporal/lib/autocomplete'>;
}
declare module 'caporal/lib/colorful.js' {
  declare module.exports: $Exports<'caporal/lib/colorful'>;
}
declare module 'caporal/lib/command.js' {
  declare module.exports: $Exports<'caporal/lib/command'>;
}
declare module 'caporal/lib/constants.js' {
  declare module.exports: $Exports<'caporal/lib/constants'>;
}
declare module 'caporal/lib/error/base-error.js' {
  declare module.exports: $Exports<'caporal/lib/error/base-error'>;
}
declare module 'caporal/lib/error/invalid-argument-value.js' {
  declare module.exports: $Exports<'caporal/lib/error/invalid-argument-value'>;
}
declare module 'caporal/lib/error/invalid-option-value.js' {
  declare module.exports: $Exports<'caporal/lib/error/invalid-option-value'>;
}
declare module 'caporal/lib/error/missing-option.js' {
  declare module.exports: $Exports<'caporal/lib/error/missing-option'>;
}
declare module 'caporal/lib/error/no-action-error.js' {
  declare module.exports: $Exports<'caporal/lib/error/no-action-error'>;
}
declare module 'caporal/lib/error/option-syntax-error.js' {
  declare module.exports: $Exports<'caporal/lib/error/option-syntax-error'>;
}
declare module 'caporal/lib/error/unknown-option.js' {
  declare module.exports: $Exports<'caporal/lib/error/unknown-option'>;
}
declare module 'caporal/lib/error/validation-error.js' {
  declare module.exports: $Exports<'caporal/lib/error/validation-error'>;
}
declare module 'caporal/lib/error/wrong-num-of-arg.js' {
  declare module.exports: $Exports<'caporal/lib/error/wrong-num-of-arg'>;
}
declare module 'caporal/lib/help.js' {
  declare module.exports: $Exports<'caporal/lib/help'>;
}
declare module 'caporal/lib/logger.js' {
  declare module.exports: $Exports<'caporal/lib/logger'>;
}
declare module 'caporal/lib/option.js' {
  declare module.exports: $Exports<'caporal/lib/option'>;
}
declare module 'caporal/lib/program.js' {
  declare module.exports: $Exports<'caporal/lib/program'>;
}
declare module 'caporal/lib/suggest.js' {
  declare module.exports: $Exports<'caporal/lib/suggest'>;
}
declare module 'caporal/lib/utils.js' {
  declare module.exports: $Exports<'caporal/lib/utils'>;
}
declare module 'caporal/lib/validator.js' {
  declare module.exports: $Exports<'caporal/lib/validator'>;
}
