// flow-typed signature: e963087b5204638e76114ab96430a436
// flow-typed version: <<STUB>>/chai-http_v^3.0.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-http/dist/chai-http' {
  declare module.exports: any;
}

declare module 'chai-http/lib/http' {
  declare module.exports: any;
}

declare module 'chai-http/lib/net' {
  declare module.exports: any;
}

declare module 'chai-http/lib/request' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-http/dist/chai-http.js' {
  declare module.exports: $Exports<'chai-http/dist/chai-http'>;
}
declare module 'chai-http/index' {
  declare module.exports: $Exports<'chai-http'>;
}
declare module 'chai-http/index.js' {
  declare module.exports: $Exports<'chai-http'>;
}
declare module 'chai-http/lib/http.js' {
  declare module.exports: $Exports<'chai-http/lib/http'>;
}
declare module 'chai-http/lib/net.js' {
  declare module.exports: $Exports<'chai-http/lib/net'>;
}
declare module 'chai-http/lib/request.js' {
  declare module.exports: $Exports<'chai-http/lib/request'>;
}
