// flow-typed signature: 632a7db0a2ff5f3f877c07c9e2b2dac8
// flow-typed version: <<STUB>>/connect_v^3.6.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'connect/index' {
  declare module.exports: $Exports<'connect'>;
}
declare module 'connect/index.js' {
  declare module.exports: $Exports<'connect'>;
}
