// flow-typed signature: 6c53c6e7e8d4fc4419f0be076eaaf6ff
// flow-typed version: <<STUB>>/connect_v^3.6.5/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'connect/index' {
  declare module.exports: $Exports<'connect'>;
}
declare module 'connect/index.js' {
  declare module.exports: $Exports<'connect'>;
}
