// flow-typed signature: b4bd19e5e2e4af3d08efb7481c74e80a
// flow-typed version: <<STUB>>/exp_v44.0.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'exp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'exp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'exp/bin/exp' {
  declare module.exports: any;
}

declare module 'exp/build/accounts' {
  declare module.exports: any;
}

declare module 'exp/build/askUser' {
  declare module.exports: any;
}

declare module 'exp/build/CommandError' {
  declare module.exports: any;
}

declare module 'exp/build/commands/android' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/AndroidBuilder' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/BaseBuilder' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/BuildError' {
  declare module.exports: any;
}

declare module 'exp/build/commands/build/IOSBuilder' {
  declare module.exports: any;
}

declare module 'exp/build/commands/convert' {
  declare module.exports: any;
}

declare module 'exp/build/commands/detach' {
  declare module.exports: any;
}

declare module 'exp/build/commands/diagnostics' {
  declare module.exports: any;
}

declare module 'exp/build/commands/doctor' {
  declare module.exports: any;
}

declare module 'exp/build/commands/fetch' {
  declare module.exports: any;
}

declare module 'exp/build/commands/init' {
  declare module.exports: any;
}

declare module 'exp/build/commands/install' {
  declare module.exports: any;
}

declare module 'exp/build/commands/ios' {
  declare module.exports: any;
}

declare module 'exp/build/commands/login' {
  declare module.exports: any;
}

declare module 'exp/build/commands/logout' {
  declare module.exports: any;
}

declare module 'exp/build/commands/path' {
  declare module.exports: any;
}

declare module 'exp/build/commands/prepare-detached-build' {
  declare module.exports: any;
}

declare module 'exp/build/commands/publish' {
  declare module.exports: any;
}

declare module 'exp/build/commands/register' {
  declare module.exports: any;
}

declare module 'exp/build/commands/send' {
  declare module.exports: any;
}

declare module 'exp/build/commands/start' {
  declare module.exports: any;
}

declare module 'exp/build/commands/test-schema' {
  declare module.exports: any;
}

declare module 'exp/build/commands/url' {
  declare module.exports: any;
}

declare module 'exp/build/commands/whoami' {
  declare module.exports: any;
}

declare module 'exp/build/debug_commands/vscode' {
  declare module.exports: any;
}

declare module 'exp/build/exit' {
  declare module.exports: any;
}

declare module 'exp/build/exp' {
  declare module.exports: any;
}

declare module 'exp/build/log' {
  declare module.exports: any;
}

declare module 'exp/build/sendTo' {
  declare module.exports: any;
}

declare module 'exp/build/update' {
  declare module.exports: any;
}

declare module 'exp/build/urlOpts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'exp/bin/exp.js' {
  declare module.exports: $Exports<'exp/bin/exp'>;
}
declare module 'exp/build/accounts.js' {
  declare module.exports: $Exports<'exp/build/accounts'>;
}
declare module 'exp/build/askUser.js' {
  declare module.exports: $Exports<'exp/build/askUser'>;
}
declare module 'exp/build/CommandError.js' {
  declare module.exports: $Exports<'exp/build/CommandError'>;
}
declare module 'exp/build/commands/android.js' {
  declare module.exports: $Exports<'exp/build/commands/android'>;
}
declare module 'exp/build/commands/build.js' {
  declare module.exports: $Exports<'exp/build/commands/build'>;
}
declare module 'exp/build/commands/build/AndroidBuilder.js' {
  declare module.exports: $Exports<'exp/build/commands/build/AndroidBuilder'>;
}
declare module 'exp/build/commands/build/BaseBuilder.js' {
  declare module.exports: $Exports<'exp/build/commands/build/BaseBuilder'>;
}
declare module 'exp/build/commands/build/BuildError.js' {
  declare module.exports: $Exports<'exp/build/commands/build/BuildError'>;
}
declare module 'exp/build/commands/build/IOSBuilder.js' {
  declare module.exports: $Exports<'exp/build/commands/build/IOSBuilder'>;
}
declare module 'exp/build/commands/convert.js' {
  declare module.exports: $Exports<'exp/build/commands/convert'>;
}
declare module 'exp/build/commands/detach.js' {
  declare module.exports: $Exports<'exp/build/commands/detach'>;
}
declare module 'exp/build/commands/diagnostics.js' {
  declare module.exports: $Exports<'exp/build/commands/diagnostics'>;
}
declare module 'exp/build/commands/doctor.js' {
  declare module.exports: $Exports<'exp/build/commands/doctor'>;
}
declare module 'exp/build/commands/fetch.js' {
  declare module.exports: $Exports<'exp/build/commands/fetch'>;
}
declare module 'exp/build/commands/init.js' {
  declare module.exports: $Exports<'exp/build/commands/init'>;
}
declare module 'exp/build/commands/install.js' {
  declare module.exports: $Exports<'exp/build/commands/install'>;
}
declare module 'exp/build/commands/ios.js' {
  declare module.exports: $Exports<'exp/build/commands/ios'>;
}
declare module 'exp/build/commands/login.js' {
  declare module.exports: $Exports<'exp/build/commands/login'>;
}
declare module 'exp/build/commands/logout.js' {
  declare module.exports: $Exports<'exp/build/commands/logout'>;
}
declare module 'exp/build/commands/path.js' {
  declare module.exports: $Exports<'exp/build/commands/path'>;
}
declare module 'exp/build/commands/prepare-detached-build.js' {
  declare module.exports: $Exports<'exp/build/commands/prepare-detached-build'>;
}
declare module 'exp/build/commands/publish.js' {
  declare module.exports: $Exports<'exp/build/commands/publish'>;
}
declare module 'exp/build/commands/register.js' {
  declare module.exports: $Exports<'exp/build/commands/register'>;
}
declare module 'exp/build/commands/send.js' {
  declare module.exports: $Exports<'exp/build/commands/send'>;
}
declare module 'exp/build/commands/start.js' {
  declare module.exports: $Exports<'exp/build/commands/start'>;
}
declare module 'exp/build/commands/test-schema.js' {
  declare module.exports: $Exports<'exp/build/commands/test-schema'>;
}
declare module 'exp/build/commands/url.js' {
  declare module.exports: $Exports<'exp/build/commands/url'>;
}
declare module 'exp/build/commands/whoami.js' {
  declare module.exports: $Exports<'exp/build/commands/whoami'>;
}
declare module 'exp/build/debug_commands/vscode.js' {
  declare module.exports: $Exports<'exp/build/debug_commands/vscode'>;
}
declare module 'exp/build/exit.js' {
  declare module.exports: $Exports<'exp/build/exit'>;
}
declare module 'exp/build/exp.js' {
  declare module.exports: $Exports<'exp/build/exp'>;
}
declare module 'exp/build/log.js' {
  declare module.exports: $Exports<'exp/build/log'>;
}
declare module 'exp/build/sendTo.js' {
  declare module.exports: $Exports<'exp/build/sendTo'>;
}
declare module 'exp/build/update.js' {
  declare module.exports: $Exports<'exp/build/update'>;
}
declare module 'exp/build/urlOpts.js' {
  declare module.exports: $Exports<'exp/build/urlOpts'>;
}
