// flow-typed signature: 4845f025fa1832603faa53cb705ea5fd
// flow-typed version: <<STUB>>/expo_v^15.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'expo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'expo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'expo/src/__tests__/Notifications-tests' {
  declare module.exports: any;
}

declare module 'expo/src/Accelerometer' {
  declare module.exports: any;
}

declare module 'expo/src/apisAreAvailable' {
  declare module.exports: any;
}

declare module 'expo/src/AppLoading.android' {
  declare module.exports: any;
}

declare module 'expo/src/AppLoading.ios' {
  declare module.exports: any;
}

declare module 'expo/src/Asset' {
  declare module.exports: any;
}

declare module 'expo/src/Audio' {
  declare module.exports: any;
}

declare module 'expo/src/BarCodeScanner' {
  declare module.exports: any;
}

declare module 'expo/src/BlurView.android' {
  declare module.exports: any;
}

declare module 'expo/src/BlurView.ios' {
  declare module.exports: any;
}

declare module 'expo/src/Constants' {
  declare module.exports: any;
}

declare module 'expo/src/Contacts' {
  declare module.exports: any;
}

declare module 'expo/src/createTHREEViewClass' {
  declare module.exports: any;
}

declare module 'expo/src/DangerZone' {
  declare module.exports: any;
}

declare module 'expo/src/Expo' {
  declare module.exports: any;
}

declare module 'expo/src/FacebookAds/AdSettings' {
  declare module.exports: any;
}

declare module 'expo/src/FacebookAds/BannerViewManager' {
  declare module.exports: any;
}

declare module 'expo/src/FacebookAds/index' {
  declare module.exports: any;
}

declare module 'expo/src/FacebookAds/InterstitialAdManager' {
  declare module.exports: any;
}

declare module 'expo/src/FacebookAds/NativeAdsManager' {
  declare module.exports: any;
}

declare module 'expo/src/FacebookAds/withNativeAd' {
  declare module.exports: any;
}

declare module 'expo/src/Font' {
  declare module.exports: any;
}

declare module 'expo/src/GLView' {
  declare module.exports: any;
}

declare module 'expo/src/Google' {
  declare module.exports: any;
}

declare module 'expo/src/Gyroscope' {
  declare module.exports: any;
}

declare module 'expo/src/Icon' {
  declare module.exports: any;
}

declare module 'expo/src/ImagePicker' {
  declare module.exports: any;
}

declare module 'expo/src/KeepAwake' {
  declare module.exports: any;
}

declare module 'expo/src/lib/createSensorWrapper' {
  declare module.exports: any;
}

declare module 'expo/src/lib/Queue' {
  declare module.exports: any;
}

declare module 'expo/src/LinearGradient.android' {
  declare module.exports: any;
}

declare module 'expo/src/LinearGradient.ios' {
  declare module.exports: any;
}

declare module 'expo/src/Location' {
  declare module.exports: any;
}

declare module 'expo/src/Logs' {
  declare module.exports: any;
}

declare module 'expo/src/Notifications' {
  declare module.exports: any;
}

declare module 'expo/src/Permissions' {
  declare module.exports: any;
}

declare module 'expo/src/registerRootComponent' {
  declare module.exports: any;
}

declare module 'expo/src/Svg' {
  declare module.exports: any;
}

declare module 'expo/src/takeSnapshotAsync' {
  declare module.exports: any;
}

declare module 'expo/src/Video' {
  declare module.exports: any;
}

declare module 'expo/tools/hashAssetFiles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'expo/src/__tests__/Notifications-tests.js' {
  declare module.exports: $Exports<'expo/src/__tests__/Notifications-tests'>;
}
declare module 'expo/src/Accelerometer.js' {
  declare module.exports: $Exports<'expo/src/Accelerometer'>;
}
declare module 'expo/src/apisAreAvailable.js' {
  declare module.exports: $Exports<'expo/src/apisAreAvailable'>;
}
declare module 'expo/src/AppLoading.android.js' {
  declare module.exports: $Exports<'expo/src/AppLoading.android'>;
}
declare module 'expo/src/AppLoading.ios.js' {
  declare module.exports: $Exports<'expo/src/AppLoading.ios'>;
}
declare module 'expo/src/Asset.js' {
  declare module.exports: $Exports<'expo/src/Asset'>;
}
declare module 'expo/src/Audio.js' {
  declare module.exports: $Exports<'expo/src/Audio'>;
}
declare module 'expo/src/BarCodeScanner.js' {
  declare module.exports: $Exports<'expo/src/BarCodeScanner'>;
}
declare module 'expo/src/BlurView.android.js' {
  declare module.exports: $Exports<'expo/src/BlurView.android'>;
}
declare module 'expo/src/BlurView.ios.js' {
  declare module.exports: $Exports<'expo/src/BlurView.ios'>;
}
declare module 'expo/src/Constants.js' {
  declare module.exports: $Exports<'expo/src/Constants'>;
}
declare module 'expo/src/Contacts.js' {
  declare module.exports: $Exports<'expo/src/Contacts'>;
}
declare module 'expo/src/createTHREEViewClass.js' {
  declare module.exports: $Exports<'expo/src/createTHREEViewClass'>;
}
declare module 'expo/src/DangerZone.js' {
  declare module.exports: $Exports<'expo/src/DangerZone'>;
}
declare module 'expo/src/Expo.js' {
  declare module.exports: $Exports<'expo/src/Expo'>;
}
declare module 'expo/src/FacebookAds/AdSettings.js' {
  declare module.exports: $Exports<'expo/src/FacebookAds/AdSettings'>;
}
declare module 'expo/src/FacebookAds/BannerViewManager.js' {
  declare module.exports: $Exports<'expo/src/FacebookAds/BannerViewManager'>;
}
declare module 'expo/src/FacebookAds/index.js' {
  declare module.exports: $Exports<'expo/src/FacebookAds/index'>;
}
declare module 'expo/src/FacebookAds/InterstitialAdManager.js' {
  declare module.exports: $Exports<'expo/src/FacebookAds/InterstitialAdManager'>;
}
declare module 'expo/src/FacebookAds/NativeAdsManager.js' {
  declare module.exports: $Exports<'expo/src/FacebookAds/NativeAdsManager'>;
}
declare module 'expo/src/FacebookAds/withNativeAd.js' {
  declare module.exports: $Exports<'expo/src/FacebookAds/withNativeAd'>;
}
declare module 'expo/src/Font.js' {
  declare module.exports: $Exports<'expo/src/Font'>;
}
declare module 'expo/src/GLView.js' {
  declare module.exports: $Exports<'expo/src/GLView'>;
}
declare module 'expo/src/Google.js' {
  declare module.exports: $Exports<'expo/src/Google'>;
}
declare module 'expo/src/Gyroscope.js' {
  declare module.exports: $Exports<'expo/src/Gyroscope'>;
}
declare module 'expo/src/Icon.js' {
  declare module.exports: $Exports<'expo/src/Icon'>;
}
declare module 'expo/src/ImagePicker.js' {
  declare module.exports: $Exports<'expo/src/ImagePicker'>;
}
declare module 'expo/src/KeepAwake.js' {
  declare module.exports: $Exports<'expo/src/KeepAwake'>;
}
declare module 'expo/src/lib/createSensorWrapper.js' {
  declare module.exports: $Exports<'expo/src/lib/createSensorWrapper'>;
}
declare module 'expo/src/lib/Queue.js' {
  declare module.exports: $Exports<'expo/src/lib/Queue'>;
}
declare module 'expo/src/LinearGradient.android.js' {
  declare module.exports: $Exports<'expo/src/LinearGradient.android'>;
}
declare module 'expo/src/LinearGradient.ios.js' {
  declare module.exports: $Exports<'expo/src/LinearGradient.ios'>;
}
declare module 'expo/src/Location.js' {
  declare module.exports: $Exports<'expo/src/Location'>;
}
declare module 'expo/src/Logs.js' {
  declare module.exports: $Exports<'expo/src/Logs'>;
}
declare module 'expo/src/Notifications.js' {
  declare module.exports: $Exports<'expo/src/Notifications'>;
}
declare module 'expo/src/Permissions.js' {
  declare module.exports: $Exports<'expo/src/Permissions'>;
}
declare module 'expo/src/registerRootComponent.js' {
  declare module.exports: $Exports<'expo/src/registerRootComponent'>;
}
declare module 'expo/src/Svg.js' {
  declare module.exports: $Exports<'expo/src/Svg'>;
}
declare module 'expo/src/takeSnapshotAsync.js' {
  declare module.exports: $Exports<'expo/src/takeSnapshotAsync'>;
}
declare module 'expo/src/Video.js' {
  declare module.exports: $Exports<'expo/src/Video'>;
}
declare module 'expo/tools/hashAssetFiles.js' {
  declare module.exports: $Exports<'expo/tools/hashAssetFiles'>;
}
