// flow-typed signature: 8240e2f417e52b2e1a80e43db69f434a
// flow-typed version: <<STUB>>/freeport-async_v^1.1.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'freeport-async'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'freeport-async' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'freeport-async/index' {
  declare module.exports: $Exports<'freeport-async'>;
}
declare module 'freeport-async/index.js' {
  declare module.exports: $Exports<'freeport-async'>;
}
