// flow-typed signature: 503a2d2f9a419d676f62db1e41e6d7d9
// flow-typed version: <<STUB>>/graphql-subscriptions_v^0.5.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-subscriptions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-subscriptions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-subscriptions/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/event-emitter-to-async-iterator' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/index' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/pubsub-engine' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/pubsub' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/subscriptions-manager' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/test/asyncIteratorSubscription' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/test/tests' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/validation' {
  declare module.exports: any;
}

declare module 'graphql-subscriptions/dist/with-filter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-subscriptions/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'graphql-subscriptions/coverage/lcov-report/prettify'>;
}
declare module 'graphql-subscriptions/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'graphql-subscriptions/coverage/lcov-report/sorter'>;
}
declare module 'graphql-subscriptions/dist/event-emitter-to-async-iterator.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/event-emitter-to-async-iterator'>;
}
declare module 'graphql-subscriptions/dist/index.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/index'>;
}
declare module 'graphql-subscriptions/dist/pubsub-engine.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/pubsub-engine'>;
}
declare module 'graphql-subscriptions/dist/pubsub.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/pubsub'>;
}
declare module 'graphql-subscriptions/dist/subscriptions-manager.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/subscriptions-manager'>;
}
declare module 'graphql-subscriptions/dist/test/asyncIteratorSubscription.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/test/asyncIteratorSubscription'>;
}
declare module 'graphql-subscriptions/dist/test/tests.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/test/tests'>;
}
declare module 'graphql-subscriptions/dist/validation.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/validation'>;
}
declare module 'graphql-subscriptions/dist/with-filter.js' {
  declare module.exports: $Exports<'graphql-subscriptions/dist/with-filter'>;
}
