// flow-typed signature: 2ad73dac224975f1059358d9508a6b6e
// flow-typed version: <<STUB>>/image-size_v^0.6.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'image-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'image-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'image-size/bin/image-size' {
  declare module.exports: any;
}

declare module 'image-size/lib/detector' {
  declare module.exports: any;
}

declare module 'image-size/lib/index' {
  declare module.exports: any;
}

declare module 'image-size/lib/readUInt' {
  declare module.exports: any;
}

declare module 'image-size/lib/types' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/bmp' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/cur' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/dds' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/gif' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/ico' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/jpg' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/png' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/psd' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/svg' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/tiff' {
  declare module.exports: any;
}

declare module 'image-size/lib/types/webp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'image-size/bin/image-size.js' {
  declare module.exports: $Exports<'image-size/bin/image-size'>;
}
declare module 'image-size/lib/detector.js' {
  declare module.exports: $Exports<'image-size/lib/detector'>;
}
declare module 'image-size/lib/index.js' {
  declare module.exports: $Exports<'image-size/lib/index'>;
}
declare module 'image-size/lib/readUInt.js' {
  declare module.exports: $Exports<'image-size/lib/readUInt'>;
}
declare module 'image-size/lib/types.js' {
  declare module.exports: $Exports<'image-size/lib/types'>;
}
declare module 'image-size/lib/types/bmp.js' {
  declare module.exports: $Exports<'image-size/lib/types/bmp'>;
}
declare module 'image-size/lib/types/cur.js' {
  declare module.exports: $Exports<'image-size/lib/types/cur'>;
}
declare module 'image-size/lib/types/dds.js' {
  declare module.exports: $Exports<'image-size/lib/types/dds'>;
}
declare module 'image-size/lib/types/gif.js' {
  declare module.exports: $Exports<'image-size/lib/types/gif'>;
}
declare module 'image-size/lib/types/ico.js' {
  declare module.exports: $Exports<'image-size/lib/types/ico'>;
}
declare module 'image-size/lib/types/jpg.js' {
  declare module.exports: $Exports<'image-size/lib/types/jpg'>;
}
declare module 'image-size/lib/types/png.js' {
  declare module.exports: $Exports<'image-size/lib/types/png'>;
}
declare module 'image-size/lib/types/psd.js' {
  declare module.exports: $Exports<'image-size/lib/types/psd'>;
}
declare module 'image-size/lib/types/svg.js' {
  declare module.exports: $Exports<'image-size/lib/types/svg'>;
}
declare module 'image-size/lib/types/tiff.js' {
  declare module.exports: $Exports<'image-size/lib/types/tiff'>;
}
declare module 'image-size/lib/types/webp.js' {
  declare module.exports: $Exports<'image-size/lib/types/webp'>;
}
