// flow-typed signature: 26014f46307f6d6571d923aeda7f3920
// flow-typed version: <<STUB>>/knex_v^0.13.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'knex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'knex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'knex/bin/cli' {
  declare module.exports: any;
}

declare module 'knex/knex' {
  declare module.exports: any;
}

declare module 'knex/lib/client' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/maria/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/maria/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mssql/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mssql/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mssql/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mssql/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mssql/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mssql/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql2/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/mysql2/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/formatter' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/schema/columnbuilder' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/schema/trigger' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracle/utils' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracledb/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracledb/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracledb/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracledb/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/oracledb/utils' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/postgres/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/postgres/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/postgres/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/postgres/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/postgres/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/sqlite3/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/sqlite3/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/sqlite3/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/sqlite3/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/sqlite3/schema/ddl' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/sqlite3/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/strong-oracle/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/websql/index' {
  declare module.exports: any;
}

declare module 'knex/lib/dialects/websql/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/formatter' {
  declare module.exports: any;
}

declare module 'knex/lib/functionhelper' {
  declare module.exports: any;
}

declare module 'knex/lib/helpers' {
  declare module.exports: any;
}

declare module 'knex/lib/index' {
  declare module.exports: any;
}

declare module 'knex/lib/interface' {
  declare module.exports: any;
}

declare module 'knex/lib/migrate/index' {
  declare module.exports: any;
}

declare module 'knex/lib/migrate/migrate-stub' {
  declare module.exports: any;
}

declare module 'knex/lib/query/builder' {
  declare module.exports: any;
}

declare module 'knex/lib/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/query/joinclause' {
  declare module.exports: any;
}

declare module 'knex/lib/query/methods' {
  declare module.exports: any;
}

declare module 'knex/lib/query/string' {
  declare module.exports: any;
}

declare module 'knex/lib/raw' {
  declare module.exports: any;
}

declare module 'knex/lib/runner' {
  declare module.exports: any;
}

declare module 'knex/lib/schema/builder' {
  declare module.exports: any;
}

declare module 'knex/lib/schema/columnbuilder' {
  declare module.exports: any;
}

declare module 'knex/lib/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/lib/schema/helpers' {
  declare module.exports: any;
}

declare module 'knex/lib/schema/tablebuilder' {
  declare module.exports: any;
}

declare module 'knex/lib/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/lib/seed/index' {
  declare module.exports: any;
}

declare module 'knex/lib/seed/seed-stub' {
  declare module.exports: any;
}

declare module 'knex/lib/transaction' {
  declare module.exports: any;
}

declare module 'knex/lib/util/batchInsert' {
  declare module.exports: any;
}

declare module 'knex/lib/util/make-knex' {
  declare module.exports: any;
}

declare module 'knex/lib/util/noop' {
  declare module.exports: any;
}

declare module 'knex/lib/util/parse-connection' {
  declare module.exports: any;
}

declare module 'knex/scripts/build' {
  declare module.exports: any;
}

declare module 'knex/src/client' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/maria/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/maria/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mssql/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mssql/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mssql/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mssql/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mssql/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mssql/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql2/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/mysql2/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/formatter' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/schema/columnbuilder' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/schema/trigger' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracle/utils' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracledb/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracledb/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracledb/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracledb/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/oracledb/utils' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/postgres/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/postgres/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/postgres/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/postgres/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/postgres/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/sqlite3/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/sqlite3/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/sqlite3/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/sqlite3/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/sqlite3/schema/ddl' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/sqlite3/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/strong-oracle/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/websql/index' {
  declare module.exports: any;
}

declare module 'knex/src/dialects/websql/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/formatter' {
  declare module.exports: any;
}

declare module 'knex/src/functionhelper' {
  declare module.exports: any;
}

declare module 'knex/src/helpers' {
  declare module.exports: any;
}

declare module 'knex/src/index' {
  declare module.exports: any;
}

declare module 'knex/src/interface' {
  declare module.exports: any;
}

declare module 'knex/src/migrate/index' {
  declare module.exports: any;
}

declare module 'knex/src/migrate/migrate-stub' {
  declare module.exports: any;
}

declare module 'knex/src/query/builder' {
  declare module.exports: any;
}

declare module 'knex/src/query/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/query/joinclause' {
  declare module.exports: any;
}

declare module 'knex/src/query/methods' {
  declare module.exports: any;
}

declare module 'knex/src/query/string' {
  declare module.exports: any;
}

declare module 'knex/src/raw' {
  declare module.exports: any;
}

declare module 'knex/src/runner' {
  declare module.exports: any;
}

declare module 'knex/src/schema/builder' {
  declare module.exports: any;
}

declare module 'knex/src/schema/columnbuilder' {
  declare module.exports: any;
}

declare module 'knex/src/schema/columncompiler' {
  declare module.exports: any;
}

declare module 'knex/src/schema/compiler' {
  declare module.exports: any;
}

declare module 'knex/src/schema/helpers' {
  declare module.exports: any;
}

declare module 'knex/src/schema/tablebuilder' {
  declare module.exports: any;
}

declare module 'knex/src/schema/tablecompiler' {
  declare module.exports: any;
}

declare module 'knex/src/seed/index' {
  declare module.exports: any;
}

declare module 'knex/src/seed/seed-stub' {
  declare module.exports: any;
}

declare module 'knex/src/transaction' {
  declare module.exports: any;
}

declare module 'knex/src/util/batchInsert' {
  declare module.exports: any;
}

declare module 'knex/src/util/make-knex' {
  declare module.exports: any;
}

declare module 'knex/src/util/noop' {
  declare module.exports: any;
}

declare module 'knex/src/util/parse-connection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'knex/bin/cli.js' {
  declare module.exports: $Exports<'knex/bin/cli'>;
}
declare module 'knex/knex.js' {
  declare module.exports: $Exports<'knex/knex'>;
}
declare module 'knex/lib/client.js' {
  declare module.exports: $Exports<'knex/lib/client'>;
}
declare module 'knex/lib/dialects/maria/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/maria/index'>;
}
declare module 'knex/lib/dialects/maria/transaction.js' {
  declare module.exports: $Exports<'knex/lib/dialects/maria/transaction'>;
}
declare module 'knex/lib/dialects/mssql/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mssql/index'>;
}
declare module 'knex/lib/dialects/mssql/query/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mssql/query/compiler'>;
}
declare module 'knex/lib/dialects/mssql/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mssql/schema/columncompiler'>;
}
declare module 'knex/lib/dialects/mssql/schema/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mssql/schema/compiler'>;
}
declare module 'knex/lib/dialects/mssql/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mssql/schema/tablecompiler'>;
}
declare module 'knex/lib/dialects/mssql/transaction.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mssql/transaction'>;
}
declare module 'knex/lib/dialects/mysql/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql/index'>;
}
declare module 'knex/lib/dialects/mysql/query/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql/query/compiler'>;
}
declare module 'knex/lib/dialects/mysql/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql/schema/columncompiler'>;
}
declare module 'knex/lib/dialects/mysql/schema/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql/schema/compiler'>;
}
declare module 'knex/lib/dialects/mysql/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql/schema/tablecompiler'>;
}
declare module 'knex/lib/dialects/mysql/transaction.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql/transaction'>;
}
declare module 'knex/lib/dialects/mysql2/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql2/index'>;
}
declare module 'knex/lib/dialects/mysql2/transaction.js' {
  declare module.exports: $Exports<'knex/lib/dialects/mysql2/transaction'>;
}
declare module 'knex/lib/dialects/oracle/formatter.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/formatter'>;
}
declare module 'knex/lib/dialects/oracle/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/index'>;
}
declare module 'knex/lib/dialects/oracle/query/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/query/compiler'>;
}
declare module 'knex/lib/dialects/oracle/schema/columnbuilder.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/schema/columnbuilder'>;
}
declare module 'knex/lib/dialects/oracle/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/schema/columncompiler'>;
}
declare module 'knex/lib/dialects/oracle/schema/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/schema/compiler'>;
}
declare module 'knex/lib/dialects/oracle/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/schema/tablecompiler'>;
}
declare module 'knex/lib/dialects/oracle/schema/trigger.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/schema/trigger'>;
}
declare module 'knex/lib/dialects/oracle/transaction.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/transaction'>;
}
declare module 'knex/lib/dialects/oracle/utils.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracle/utils'>;
}
declare module 'knex/lib/dialects/oracledb/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracledb/index'>;
}
declare module 'knex/lib/dialects/oracledb/query/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracledb/query/compiler'>;
}
declare module 'knex/lib/dialects/oracledb/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracledb/schema/columncompiler'>;
}
declare module 'knex/lib/dialects/oracledb/transaction.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracledb/transaction'>;
}
declare module 'knex/lib/dialects/oracledb/utils.js' {
  declare module.exports: $Exports<'knex/lib/dialects/oracledb/utils'>;
}
declare module 'knex/lib/dialects/postgres/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/postgres/index'>;
}
declare module 'knex/lib/dialects/postgres/query/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/postgres/query/compiler'>;
}
declare module 'knex/lib/dialects/postgres/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/postgres/schema/columncompiler'>;
}
declare module 'knex/lib/dialects/postgres/schema/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/postgres/schema/compiler'>;
}
declare module 'knex/lib/dialects/postgres/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/postgres/schema/tablecompiler'>;
}
declare module 'knex/lib/dialects/sqlite3/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/sqlite3/index'>;
}
declare module 'knex/lib/dialects/sqlite3/query/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/sqlite3/query/compiler'>;
}
declare module 'knex/lib/dialects/sqlite3/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/sqlite3/schema/columncompiler'>;
}
declare module 'knex/lib/dialects/sqlite3/schema/compiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/sqlite3/schema/compiler'>;
}
declare module 'knex/lib/dialects/sqlite3/schema/ddl.js' {
  declare module.exports: $Exports<'knex/lib/dialects/sqlite3/schema/ddl'>;
}
declare module 'knex/lib/dialects/sqlite3/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/lib/dialects/sqlite3/schema/tablecompiler'>;
}
declare module 'knex/lib/dialects/strong-oracle/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/strong-oracle/index'>;
}
declare module 'knex/lib/dialects/websql/index.js' {
  declare module.exports: $Exports<'knex/lib/dialects/websql/index'>;
}
declare module 'knex/lib/dialects/websql/transaction.js' {
  declare module.exports: $Exports<'knex/lib/dialects/websql/transaction'>;
}
declare module 'knex/lib/formatter.js' {
  declare module.exports: $Exports<'knex/lib/formatter'>;
}
declare module 'knex/lib/functionhelper.js' {
  declare module.exports: $Exports<'knex/lib/functionhelper'>;
}
declare module 'knex/lib/helpers.js' {
  declare module.exports: $Exports<'knex/lib/helpers'>;
}
declare module 'knex/lib/index.js' {
  declare module.exports: $Exports<'knex/lib/index'>;
}
declare module 'knex/lib/interface.js' {
  declare module.exports: $Exports<'knex/lib/interface'>;
}
declare module 'knex/lib/migrate/index.js' {
  declare module.exports: $Exports<'knex/lib/migrate/index'>;
}
declare module 'knex/lib/migrate/migrate-stub.js' {
  declare module.exports: $Exports<'knex/lib/migrate/migrate-stub'>;
}
declare module 'knex/lib/query/builder.js' {
  declare module.exports: $Exports<'knex/lib/query/builder'>;
}
declare module 'knex/lib/query/compiler.js' {
  declare module.exports: $Exports<'knex/lib/query/compiler'>;
}
declare module 'knex/lib/query/joinclause.js' {
  declare module.exports: $Exports<'knex/lib/query/joinclause'>;
}
declare module 'knex/lib/query/methods.js' {
  declare module.exports: $Exports<'knex/lib/query/methods'>;
}
declare module 'knex/lib/query/string.js' {
  declare module.exports: $Exports<'knex/lib/query/string'>;
}
declare module 'knex/lib/raw.js' {
  declare module.exports: $Exports<'knex/lib/raw'>;
}
declare module 'knex/lib/runner.js' {
  declare module.exports: $Exports<'knex/lib/runner'>;
}
declare module 'knex/lib/schema/builder.js' {
  declare module.exports: $Exports<'knex/lib/schema/builder'>;
}
declare module 'knex/lib/schema/columnbuilder.js' {
  declare module.exports: $Exports<'knex/lib/schema/columnbuilder'>;
}
declare module 'knex/lib/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/lib/schema/columncompiler'>;
}
declare module 'knex/lib/schema/compiler.js' {
  declare module.exports: $Exports<'knex/lib/schema/compiler'>;
}
declare module 'knex/lib/schema/helpers.js' {
  declare module.exports: $Exports<'knex/lib/schema/helpers'>;
}
declare module 'knex/lib/schema/tablebuilder.js' {
  declare module.exports: $Exports<'knex/lib/schema/tablebuilder'>;
}
declare module 'knex/lib/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/lib/schema/tablecompiler'>;
}
declare module 'knex/lib/seed/index.js' {
  declare module.exports: $Exports<'knex/lib/seed/index'>;
}
declare module 'knex/lib/seed/seed-stub.js' {
  declare module.exports: $Exports<'knex/lib/seed/seed-stub'>;
}
declare module 'knex/lib/transaction.js' {
  declare module.exports: $Exports<'knex/lib/transaction'>;
}
declare module 'knex/lib/util/batchInsert.js' {
  declare module.exports: $Exports<'knex/lib/util/batchInsert'>;
}
declare module 'knex/lib/util/make-knex.js' {
  declare module.exports: $Exports<'knex/lib/util/make-knex'>;
}
declare module 'knex/lib/util/noop.js' {
  declare module.exports: $Exports<'knex/lib/util/noop'>;
}
declare module 'knex/lib/util/parse-connection.js' {
  declare module.exports: $Exports<'knex/lib/util/parse-connection'>;
}
declare module 'knex/scripts/build.js' {
  declare module.exports: $Exports<'knex/scripts/build'>;
}
declare module 'knex/src/client.js' {
  declare module.exports: $Exports<'knex/src/client'>;
}
declare module 'knex/src/dialects/maria/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/maria/index'>;
}
declare module 'knex/src/dialects/maria/transaction.js' {
  declare module.exports: $Exports<'knex/src/dialects/maria/transaction'>;
}
declare module 'knex/src/dialects/mssql/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/mssql/index'>;
}
declare module 'knex/src/dialects/mssql/query/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mssql/query/compiler'>;
}
declare module 'knex/src/dialects/mssql/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mssql/schema/columncompiler'>;
}
declare module 'knex/src/dialects/mssql/schema/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mssql/schema/compiler'>;
}
declare module 'knex/src/dialects/mssql/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mssql/schema/tablecompiler'>;
}
declare module 'knex/src/dialects/mssql/transaction.js' {
  declare module.exports: $Exports<'knex/src/dialects/mssql/transaction'>;
}
declare module 'knex/src/dialects/mysql/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql/index'>;
}
declare module 'knex/src/dialects/mysql/query/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql/query/compiler'>;
}
declare module 'knex/src/dialects/mysql/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql/schema/columncompiler'>;
}
declare module 'knex/src/dialects/mysql/schema/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql/schema/compiler'>;
}
declare module 'knex/src/dialects/mysql/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql/schema/tablecompiler'>;
}
declare module 'knex/src/dialects/mysql/transaction.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql/transaction'>;
}
declare module 'knex/src/dialects/mysql2/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql2/index'>;
}
declare module 'knex/src/dialects/mysql2/transaction.js' {
  declare module.exports: $Exports<'knex/src/dialects/mysql2/transaction'>;
}
declare module 'knex/src/dialects/oracle/formatter.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/formatter'>;
}
declare module 'knex/src/dialects/oracle/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/index'>;
}
declare module 'knex/src/dialects/oracle/query/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/query/compiler'>;
}
declare module 'knex/src/dialects/oracle/schema/columnbuilder.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/schema/columnbuilder'>;
}
declare module 'knex/src/dialects/oracle/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/schema/columncompiler'>;
}
declare module 'knex/src/dialects/oracle/schema/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/schema/compiler'>;
}
declare module 'knex/src/dialects/oracle/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/schema/tablecompiler'>;
}
declare module 'knex/src/dialects/oracle/schema/trigger.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/schema/trigger'>;
}
declare module 'knex/src/dialects/oracle/transaction.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/transaction'>;
}
declare module 'knex/src/dialects/oracle/utils.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracle/utils'>;
}
declare module 'knex/src/dialects/oracledb/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracledb/index'>;
}
declare module 'knex/src/dialects/oracledb/query/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracledb/query/compiler'>;
}
declare module 'knex/src/dialects/oracledb/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracledb/schema/columncompiler'>;
}
declare module 'knex/src/dialects/oracledb/transaction.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracledb/transaction'>;
}
declare module 'knex/src/dialects/oracledb/utils.js' {
  declare module.exports: $Exports<'knex/src/dialects/oracledb/utils'>;
}
declare module 'knex/src/dialects/postgres/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/postgres/index'>;
}
declare module 'knex/src/dialects/postgres/query/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/postgres/query/compiler'>;
}
declare module 'knex/src/dialects/postgres/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/postgres/schema/columncompiler'>;
}
declare module 'knex/src/dialects/postgres/schema/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/postgres/schema/compiler'>;
}
declare module 'knex/src/dialects/postgres/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/postgres/schema/tablecompiler'>;
}
declare module 'knex/src/dialects/sqlite3/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/sqlite3/index'>;
}
declare module 'knex/src/dialects/sqlite3/query/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/sqlite3/query/compiler'>;
}
declare module 'knex/src/dialects/sqlite3/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/sqlite3/schema/columncompiler'>;
}
declare module 'knex/src/dialects/sqlite3/schema/compiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/sqlite3/schema/compiler'>;
}
declare module 'knex/src/dialects/sqlite3/schema/ddl.js' {
  declare module.exports: $Exports<'knex/src/dialects/sqlite3/schema/ddl'>;
}
declare module 'knex/src/dialects/sqlite3/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/src/dialects/sqlite3/schema/tablecompiler'>;
}
declare module 'knex/src/dialects/strong-oracle/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/strong-oracle/index'>;
}
declare module 'knex/src/dialects/websql/index.js' {
  declare module.exports: $Exports<'knex/src/dialects/websql/index'>;
}
declare module 'knex/src/dialects/websql/transaction.js' {
  declare module.exports: $Exports<'knex/src/dialects/websql/transaction'>;
}
declare module 'knex/src/formatter.js' {
  declare module.exports: $Exports<'knex/src/formatter'>;
}
declare module 'knex/src/functionhelper.js' {
  declare module.exports: $Exports<'knex/src/functionhelper'>;
}
declare module 'knex/src/helpers.js' {
  declare module.exports: $Exports<'knex/src/helpers'>;
}
declare module 'knex/src/index.js' {
  declare module.exports: $Exports<'knex/src/index'>;
}
declare module 'knex/src/interface.js' {
  declare module.exports: $Exports<'knex/src/interface'>;
}
declare module 'knex/src/migrate/index.js' {
  declare module.exports: $Exports<'knex/src/migrate/index'>;
}
declare module 'knex/src/migrate/migrate-stub.js' {
  declare module.exports: $Exports<'knex/src/migrate/migrate-stub'>;
}
declare module 'knex/src/query/builder.js' {
  declare module.exports: $Exports<'knex/src/query/builder'>;
}
declare module 'knex/src/query/compiler.js' {
  declare module.exports: $Exports<'knex/src/query/compiler'>;
}
declare module 'knex/src/query/joinclause.js' {
  declare module.exports: $Exports<'knex/src/query/joinclause'>;
}
declare module 'knex/src/query/methods.js' {
  declare module.exports: $Exports<'knex/src/query/methods'>;
}
declare module 'knex/src/query/string.js' {
  declare module.exports: $Exports<'knex/src/query/string'>;
}
declare module 'knex/src/raw.js' {
  declare module.exports: $Exports<'knex/src/raw'>;
}
declare module 'knex/src/runner.js' {
  declare module.exports: $Exports<'knex/src/runner'>;
}
declare module 'knex/src/schema/builder.js' {
  declare module.exports: $Exports<'knex/src/schema/builder'>;
}
declare module 'knex/src/schema/columnbuilder.js' {
  declare module.exports: $Exports<'knex/src/schema/columnbuilder'>;
}
declare module 'knex/src/schema/columncompiler.js' {
  declare module.exports: $Exports<'knex/src/schema/columncompiler'>;
}
declare module 'knex/src/schema/compiler.js' {
  declare module.exports: $Exports<'knex/src/schema/compiler'>;
}
declare module 'knex/src/schema/helpers.js' {
  declare module.exports: $Exports<'knex/src/schema/helpers'>;
}
declare module 'knex/src/schema/tablebuilder.js' {
  declare module.exports: $Exports<'knex/src/schema/tablebuilder'>;
}
declare module 'knex/src/schema/tablecompiler.js' {
  declare module.exports: $Exports<'knex/src/schema/tablecompiler'>;
}
declare module 'knex/src/seed/index.js' {
  declare module.exports: $Exports<'knex/src/seed/index'>;
}
declare module 'knex/src/seed/seed-stub.js' {
  declare module.exports: $Exports<'knex/src/seed/seed-stub'>;
}
declare module 'knex/src/transaction.js' {
  declare module.exports: $Exports<'knex/src/transaction'>;
}
declare module 'knex/src/util/batchInsert.js' {
  declare module.exports: $Exports<'knex/src/util/batchInsert'>;
}
declare module 'knex/src/util/make-knex.js' {
  declare module.exports: $Exports<'knex/src/util/make-knex'>;
}
declare module 'knex/src/util/noop.js' {
  declare module.exports: $Exports<'knex/src/util/noop'>;
}
declare module 'knex/src/util/parse-connection.js' {
  declare module.exports: $Exports<'knex/src/util/parse-connection'>;
}
