// flow-typed signature: cf811abfba0f2586872a0268bd328ce0
// flow-typed version: <<STUB>>/minilog_v^3.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minilog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minilog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'minilog/dist/minilog' {
  declare module.exports: any;
}

declare module 'minilog/lib/common/filter' {
  declare module.exports: any;
}

declare module 'minilog/lib/common/minilog' {
  declare module.exports: any;
}

declare module 'minilog/lib/common/transform' {
  declare module.exports: any;
}

declare module 'minilog/lib/index' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/console' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/clean' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/color' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/learnboost' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/minilog' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/npm' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/time' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/util' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/formatters/withstack' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/redis' {
  declare module.exports: any;
}

declare module 'minilog/lib/node/stringify' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/array' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/console' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/formatters/color' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/formatters/minilog' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/formatters/util' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/index' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/jquery_simple' {
  declare module.exports: any;
}

declare module 'minilog/lib/web/localstorage' {
  declare module.exports: any;
}

declare module 'minilog/test/example/jquery_server' {
  declare module.exports: any;
}

declare module 'minilog/test/example/themes_example' {
  declare module.exports: any;
}

declare module 'minilog/test/example/whitelist_example' {
  declare module.exports: any;
}

declare module 'minilog/test/filter.test' {
  declare module.exports: any;
}

declare module 'minilog/test/lib/localstorage' {
  declare module.exports: any;
}

declare module 'minilog/test/minilog.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'minilog/dist/minilog.js' {
  declare module.exports: $Exports<'minilog/dist/minilog'>;
}
declare module 'minilog/lib/common/filter.js' {
  declare module.exports: $Exports<'minilog/lib/common/filter'>;
}
declare module 'minilog/lib/common/minilog.js' {
  declare module.exports: $Exports<'minilog/lib/common/minilog'>;
}
declare module 'minilog/lib/common/transform.js' {
  declare module.exports: $Exports<'minilog/lib/common/transform'>;
}
declare module 'minilog/lib/index.js' {
  declare module.exports: $Exports<'minilog/lib/index'>;
}
declare module 'minilog/lib/node/console.js' {
  declare module.exports: $Exports<'minilog/lib/node/console'>;
}
declare module 'minilog/lib/node/formatters/clean.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/clean'>;
}
declare module 'minilog/lib/node/formatters/color.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/color'>;
}
declare module 'minilog/lib/node/formatters/learnboost.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/learnboost'>;
}
declare module 'minilog/lib/node/formatters/minilog.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/minilog'>;
}
declare module 'minilog/lib/node/formatters/npm.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/npm'>;
}
declare module 'minilog/lib/node/formatters/time.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/time'>;
}
declare module 'minilog/lib/node/formatters/util.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/util'>;
}
declare module 'minilog/lib/node/formatters/withstack.js' {
  declare module.exports: $Exports<'minilog/lib/node/formatters/withstack'>;
}
declare module 'minilog/lib/node/redis.js' {
  declare module.exports: $Exports<'minilog/lib/node/redis'>;
}
declare module 'minilog/lib/node/stringify.js' {
  declare module.exports: $Exports<'minilog/lib/node/stringify'>;
}
declare module 'minilog/lib/web/array.js' {
  declare module.exports: $Exports<'minilog/lib/web/array'>;
}
declare module 'minilog/lib/web/console.js' {
  declare module.exports: $Exports<'minilog/lib/web/console'>;
}
declare module 'minilog/lib/web/formatters/color.js' {
  declare module.exports: $Exports<'minilog/lib/web/formatters/color'>;
}
declare module 'minilog/lib/web/formatters/minilog.js' {
  declare module.exports: $Exports<'minilog/lib/web/formatters/minilog'>;
}
declare module 'minilog/lib/web/formatters/util.js' {
  declare module.exports: $Exports<'minilog/lib/web/formatters/util'>;
}
declare module 'minilog/lib/web/index.js' {
  declare module.exports: $Exports<'minilog/lib/web/index'>;
}
declare module 'minilog/lib/web/jquery_simple.js' {
  declare module.exports: $Exports<'minilog/lib/web/jquery_simple'>;
}
declare module 'minilog/lib/web/localstorage.js' {
  declare module.exports: $Exports<'minilog/lib/web/localstorage'>;
}
declare module 'minilog/test/example/jquery_server.js' {
  declare module.exports: $Exports<'minilog/test/example/jquery_server'>;
}
declare module 'minilog/test/example/themes_example.js' {
  declare module.exports: $Exports<'minilog/test/example/themes_example'>;
}
declare module 'minilog/test/example/whitelist_example.js' {
  declare module.exports: $Exports<'minilog/test/example/whitelist_example'>;
}
declare module 'minilog/test/filter.test.js' {
  declare module.exports: $Exports<'minilog/test/filter.test'>;
}
declare module 'minilog/test/lib/localstorage.js' {
  declare module.exports: $Exports<'minilog/test/lib/localstorage'>;
}
declare module 'minilog/test/minilog.test.js' {
  declare module.exports: $Exports<'minilog/test/minilog.test'>;
}
