// flow-typed signature: 61c437d5bb878295f28c88467ba1379e
// flow-typed version: <<STUB>>/mocha-webpack_v^0.7.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-webpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-webpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-webpack/lib/cli/index' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/parseArgv' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/parseConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/prepareWebpack' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/requireWebpackConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/cli/runner' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/mocha/checkReporter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/mocha/configureMocha' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/mocha/resetMocha' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/reporters/base' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/util/exists' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/utils' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/build' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/contextReplacementPlugin' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/createCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/includeFilesLoader' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/InjectChangedFilesPlugin' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/prepareEntry' {
  declare module.exports: any;
}

declare module 'mocha-webpack/lib/webpack/watch' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/index' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/parseArgv' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/parseConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/prepareWebpack' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/requireWebpackConfig' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/cli/runner' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/mocha/checkReporter' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/mocha/configureMocha' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/mocha/resetMocha' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/util/exists' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/build' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/contextReplacementPlugin' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/createCompiler' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/includeFilesLoader' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/InjectChangedFilesPlugin' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/prepareEntry' {
  declare module.exports: any;
}

declare module 'mocha-webpack/src/webpack/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-webpack/lib/cli/index.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/index'>;
}
declare module 'mocha-webpack/lib/cli/parseArgv.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/parseArgv'>;
}
declare module 'mocha-webpack/lib/cli/parseConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/parseConfig'>;
}
declare module 'mocha-webpack/lib/cli/prepareWebpack.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/prepareWebpack'>;
}
declare module 'mocha-webpack/lib/cli/requireWebpackConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/requireWebpackConfig'>;
}
declare module 'mocha-webpack/lib/cli/runner.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/cli/runner'>;
}
declare module 'mocha-webpack/lib/mocha/checkReporter.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/mocha/checkReporter'>;
}
declare module 'mocha-webpack/lib/mocha/configureMocha.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/mocha/configureMocha'>;
}
declare module 'mocha-webpack/lib/mocha/resetMocha.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/mocha/resetMocha'>;
}
declare module 'mocha-webpack/lib/reporters/base.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/reporters/base'>;
}
declare module 'mocha-webpack/lib/util/exists.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/util/exists'>;
}
declare module 'mocha-webpack/lib/utils.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/utils'>;
}
declare module 'mocha-webpack/lib/webpack/build.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/build'>;
}
declare module 'mocha-webpack/lib/webpack/contextReplacementPlugin.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/contextReplacementPlugin'>;
}
declare module 'mocha-webpack/lib/webpack/createCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/createCompiler'>;
}
declare module 'mocha-webpack/lib/webpack/includeFilesLoader.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/includeFilesLoader'>;
}
declare module 'mocha-webpack/lib/webpack/InjectChangedFilesPlugin.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/InjectChangedFilesPlugin'>;
}
declare module 'mocha-webpack/lib/webpack/prepareEntry.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/prepareEntry'>;
}
declare module 'mocha-webpack/lib/webpack/watch.js' {
  declare module.exports: $Exports<'mocha-webpack/lib/webpack/watch'>;
}
declare module 'mocha-webpack/src/cli/index.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/index'>;
}
declare module 'mocha-webpack/src/cli/parseArgv.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/parseArgv'>;
}
declare module 'mocha-webpack/src/cli/parseConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/parseConfig'>;
}
declare module 'mocha-webpack/src/cli/prepareWebpack.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/prepareWebpack'>;
}
declare module 'mocha-webpack/src/cli/requireWebpackConfig.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/requireWebpackConfig'>;
}
declare module 'mocha-webpack/src/cli/runner.js' {
  declare module.exports: $Exports<'mocha-webpack/src/cli/runner'>;
}
declare module 'mocha-webpack/src/mocha/checkReporter.js' {
  declare module.exports: $Exports<'mocha-webpack/src/mocha/checkReporter'>;
}
declare module 'mocha-webpack/src/mocha/configureMocha.js' {
  declare module.exports: $Exports<'mocha-webpack/src/mocha/configureMocha'>;
}
declare module 'mocha-webpack/src/mocha/resetMocha.js' {
  declare module.exports: $Exports<'mocha-webpack/src/mocha/resetMocha'>;
}
declare module 'mocha-webpack/src/util/exists.js' {
  declare module.exports: $Exports<'mocha-webpack/src/util/exists'>;
}
declare module 'mocha-webpack/src/webpack/build.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/build'>;
}
declare module 'mocha-webpack/src/webpack/contextReplacementPlugin.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/contextReplacementPlugin'>;
}
declare module 'mocha-webpack/src/webpack/createCompiler.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/createCompiler'>;
}
declare module 'mocha-webpack/src/webpack/includeFilesLoader.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/includeFilesLoader'>;
}
declare module 'mocha-webpack/src/webpack/InjectChangedFilesPlugin.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/InjectChangedFilesPlugin'>;
}
declare module 'mocha-webpack/src/webpack/prepareEntry.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/prepareEntry'>;
}
declare module 'mocha-webpack/src/webpack/watch.js' {
  declare module.exports: $Exports<'mocha-webpack/src/webpack/watch'>;
}
