// flow-typed signature: 64443858f42019a4fb12633a3b325bbb
// flow-typed version: <<STUB>>/mocha-steps_v^1.1.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mocha-steps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mocha-steps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'mocha-steps/lib/step' {
  declare module.exports: any;
}

// Filename aliases
declare module 'mocha-steps/lib/step.js' {
  declare module.exports: $Exports<'mocha-steps/lib/step'>;
}
