// flow-typed signature: a84e240173af053fbc6f05d56eced3ff
// flow-typed version: <<STUB>>/openurl_v^1.1.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'openurl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'openurl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'openurl/openurl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'openurl/openurl.js' {
  declare module.exports: $Exports<'openurl/openurl'>;
}
