// flow-typed signature: c96e990212446d79d284ef8c1fd83a4c
// flow-typed version: <<STUB>>/persistgraphql_v^0.4.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'persistgraphql'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'persistgraphql' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'persistgraphql/lib/index' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/binary' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/common' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/extractFromAST' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/extractFromJS' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/ExtractGQL' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/network_interface/ApolloNetworkInterface' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/src/queryTransformers' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/common' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/extractFromAST' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/extractFromJS' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/index' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/network_interface/ApolloNetworkInterface' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/queryTransformers' {
  declare module.exports: any;
}

declare module 'persistgraphql/lib/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'persistgraphql/lib/index.js' {
  declare module.exports: $Exports<'persistgraphql/lib/index'>;
}
declare module 'persistgraphql/lib/src/binary.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/binary'>;
}
declare module 'persistgraphql/lib/src/common.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/common'>;
}
declare module 'persistgraphql/lib/src/extractFromAST.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/extractFromAST'>;
}
declare module 'persistgraphql/lib/src/extractFromJS.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/extractFromJS'>;
}
declare module 'persistgraphql/lib/src/ExtractGQL.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/ExtractGQL'>;
}
declare module 'persistgraphql/lib/src/network_interface/ApolloNetworkInterface.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/network_interface/ApolloNetworkInterface'>;
}
declare module 'persistgraphql/lib/src/queryTransformers.js' {
  declare module.exports: $Exports<'persistgraphql/lib/src/queryTransformers'>;
}
declare module 'persistgraphql/lib/test/common.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/common'>;
}
declare module 'persistgraphql/lib/test/extractFromAST.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/extractFromAST'>;
}
declare module 'persistgraphql/lib/test/extractFromJS.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/extractFromJS'>;
}
declare module 'persistgraphql/lib/test/index.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/index'>;
}
declare module 'persistgraphql/lib/test/network_interface/ApolloNetworkInterface.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/network_interface/ApolloNetworkInterface'>;
}
declare module 'persistgraphql/lib/test/queryTransformers.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/queryTransformers'>;
}
declare module 'persistgraphql/lib/test/tests.js' {
  declare module.exports: $Exports<'persistgraphql/lib/test/tests'>;
}
