// flow-typed signature: ca9d49fcaa7e562cf9148ee372884bf2
// flow-typed version: <<STUB>>/persistgraphql-webpack-plugin_v^0.4.2/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'persistgraphql-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'persistgraphql-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'persistgraphql-webpack-plugin/graphql-loader' {
  declare module.exports: any;
}

declare module 'persistgraphql-webpack-plugin/js-loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'persistgraphql-webpack-plugin/graphql-loader.js' {
  declare module.exports: $Exports<'persistgraphql-webpack-plugin/graphql-loader'>;
}
declare module 'persistgraphql-webpack-plugin/index' {
  declare module.exports: $Exports<'persistgraphql-webpack-plugin'>;
}
declare module 'persistgraphql-webpack-plugin/index.js' {
  declare module.exports: $Exports<'persistgraphql-webpack-plugin'>;
}
declare module 'persistgraphql-webpack-plugin/js-loader.js' {
  declare module.exports: $Exports<'persistgraphql-webpack-plugin/js-loader'>;
}
