// flow-typed signature: 1fc07b462c1cc4c62a11fa0fe59c4978
// flow-typed version: <<STUB>>/qrcode-terminal_v^0.11.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'qrcode-terminal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'qrcode-terminal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'qrcode-terminal/bin/qrcode-terminal' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/example/basic' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/example/callback' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/example/small-qrcode' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/lib/main' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/test/main' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/index' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QR8bitByte' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRBitBuffer' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRErrorCorrectLevel' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRMaskPattern' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRMath' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRMode' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRPolynomial' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRRSBlock' {
  declare module.exports: any;
}

declare module 'qrcode-terminal/vendor/QRCode/QRUtil' {
  declare module.exports: any;
}

// Filename aliases
declare module 'qrcode-terminal/bin/qrcode-terminal.js' {
  declare module.exports: $Exports<'qrcode-terminal/bin/qrcode-terminal'>;
}
declare module 'qrcode-terminal/example/basic.js' {
  declare module.exports: $Exports<'qrcode-terminal/example/basic'>;
}
declare module 'qrcode-terminal/example/callback.js' {
  declare module.exports: $Exports<'qrcode-terminal/example/callback'>;
}
declare module 'qrcode-terminal/example/small-qrcode.js' {
  declare module.exports: $Exports<'qrcode-terminal/example/small-qrcode'>;
}
declare module 'qrcode-terminal/lib/main.js' {
  declare module.exports: $Exports<'qrcode-terminal/lib/main'>;
}
declare module 'qrcode-terminal/test/main.js' {
  declare module.exports: $Exports<'qrcode-terminal/test/main'>;
}
declare module 'qrcode-terminal/vendor/QRCode/index.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/index'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QR8bitByte.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QR8bitByte'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRBitBuffer.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRBitBuffer'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRErrorCorrectLevel.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRErrorCorrectLevel'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRMaskPattern.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRMaskPattern'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRMath.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRMath'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRMode.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRMode'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRPolynomial.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRPolynomial'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRRSBlock.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRRSBlock'>;
}
declare module 'qrcode-terminal/vendor/QRCode/QRUtil.js' {
  declare module.exports: $Exports<'qrcode-terminal/vendor/QRCode/QRUtil'>;
}
