// flow-typed signature: 67f07481772ea059bc7bce14569eccc7
// flow-typed version: <<STUB>>/react-ga_v^2.2.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ga/dist/react-ga' {
  declare module.exports: any;
}

declare module 'react-ga/dist/react-ga.min' {
  declare module.exports: any;
}

declare module 'react-ga/gulpfile' {
  declare module.exports: any;
}

declare module 'react-ga/src/components/OutboundLink' {
  declare module.exports: any;
}

declare module 'react-ga/src/index' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/console/log' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/console/warn' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/format' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/mightBeEmail' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/removeLeadingSlash' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/toTitleCase' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/trim' {
  declare module.exports: any;
}

declare module 'react-ga/test/components/OutboundLink.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/index.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/utils/console/log.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/utils/console/warn.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/utils/format.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/utils/mightBeEmail.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/utils/removeLeadingSlash.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/utils/toTitleCase.test' {
  declare module.exports: any;
}

declare module 'react-ga/test/utils/trim.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ga/dist/react-ga.js' {
  declare module.exports: $Exports<'react-ga/dist/react-ga'>;
}
declare module 'react-ga/dist/react-ga.min.js' {
  declare module.exports: $Exports<'react-ga/dist/react-ga.min'>;
}
declare module 'react-ga/gulpfile.js' {
  declare module.exports: $Exports<'react-ga/gulpfile'>;
}
declare module 'react-ga/src/components/OutboundLink.js' {
  declare module.exports: $Exports<'react-ga/src/components/OutboundLink'>;
}
declare module 'react-ga/src/index.js' {
  declare module.exports: $Exports<'react-ga/src/index'>;
}
declare module 'react-ga/src/utils/console/log.js' {
  declare module.exports: $Exports<'react-ga/src/utils/console/log'>;
}
declare module 'react-ga/src/utils/console/warn.js' {
  declare module.exports: $Exports<'react-ga/src/utils/console/warn'>;
}
declare module 'react-ga/src/utils/format.js' {
  declare module.exports: $Exports<'react-ga/src/utils/format'>;
}
declare module 'react-ga/src/utils/mightBeEmail.js' {
  declare module.exports: $Exports<'react-ga/src/utils/mightBeEmail'>;
}
declare module 'react-ga/src/utils/removeLeadingSlash.js' {
  declare module.exports: $Exports<'react-ga/src/utils/removeLeadingSlash'>;
}
declare module 'react-ga/src/utils/toTitleCase.js' {
  declare module.exports: $Exports<'react-ga/src/utils/toTitleCase'>;
}
declare module 'react-ga/src/utils/trim.js' {
  declare module.exports: $Exports<'react-ga/src/utils/trim'>;
}
declare module 'react-ga/test/components/OutboundLink.test.js' {
  declare module.exports: $Exports<'react-ga/test/components/OutboundLink.test'>;
}
declare module 'react-ga/test/index.test.js' {
  declare module.exports: $Exports<'react-ga/test/index.test'>;
}
declare module 'react-ga/test/utils/console/log.test.js' {
  declare module.exports: $Exports<'react-ga/test/utils/console/log.test'>;
}
declare module 'react-ga/test/utils/console/warn.test.js' {
  declare module.exports: $Exports<'react-ga/test/utils/console/warn.test'>;
}
declare module 'react-ga/test/utils/format.test.js' {
  declare module.exports: $Exports<'react-ga/test/utils/format.test'>;
}
declare module 'react-ga/test/utils/mightBeEmail.test.js' {
  declare module.exports: $Exports<'react-ga/test/utils/mightBeEmail.test'>;
}
declare module 'react-ga/test/utils/removeLeadingSlash.test.js' {
  declare module.exports: $Exports<'react-ga/test/utils/removeLeadingSlash.test'>;
}
declare module 'react-ga/test/utils/toTitleCase.test.js' {
  declare module.exports: $Exports<'react-ga/test/utils/toTitleCase.test'>;
}
declare module 'react-ga/test/utils/trim.test.js' {
  declare module.exports: $Exports<'react-ga/test/utils/trim.test'>;
}
