// flow-typed signature: 1ae9aa271c09646be95e45c7a9104f26
// flow-typed version: <<STUB>>/react-ga_v^2.3.5/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-ga'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-ga' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-ga/dist/react-ga' {
  declare module.exports: any;
}

declare module 'react-ga/dist/react-ga.min' {
  declare module.exports: any;
}

declare module 'react-ga/src/components/OutboundLink' {
  declare module.exports: any;
}

declare module 'react-ga/src/index' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/console/log' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/console/warn' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/format' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/loadGA' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/mightBeEmail' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/removeLeadingSlash' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/toTitleCase' {
  declare module.exports: any;
}

declare module 'react-ga/src/utils/trim' {
  declare module.exports: any;
}

declare module 'react-ga/version-bower' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-ga/dist/react-ga.js' {
  declare module.exports: $Exports<'react-ga/dist/react-ga'>;
}
declare module 'react-ga/dist/react-ga.min.js' {
  declare module.exports: $Exports<'react-ga/dist/react-ga.min'>;
}
declare module 'react-ga/src/components/OutboundLink.js' {
  declare module.exports: $Exports<'react-ga/src/components/OutboundLink'>;
}
declare module 'react-ga/src/index.js' {
  declare module.exports: $Exports<'react-ga/src/index'>;
}
declare module 'react-ga/src/utils/console/log.js' {
  declare module.exports: $Exports<'react-ga/src/utils/console/log'>;
}
declare module 'react-ga/src/utils/console/warn.js' {
  declare module.exports: $Exports<'react-ga/src/utils/console/warn'>;
}
declare module 'react-ga/src/utils/format.js' {
  declare module.exports: $Exports<'react-ga/src/utils/format'>;
}
declare module 'react-ga/src/utils/loadGA.js' {
  declare module.exports: $Exports<'react-ga/src/utils/loadGA'>;
}
declare module 'react-ga/src/utils/mightBeEmail.js' {
  declare module.exports: $Exports<'react-ga/src/utils/mightBeEmail'>;
}
declare module 'react-ga/src/utils/removeLeadingSlash.js' {
  declare module.exports: $Exports<'react-ga/src/utils/removeLeadingSlash'>;
}
declare module 'react-ga/src/utils/toTitleCase.js' {
  declare module.exports: $Exports<'react-ga/src/utils/toTitleCase'>;
}
declare module 'react-ga/src/utils/trim.js' {
  declare module.exports: $Exports<'react-ga/src/utils/trim'>;
}
declare module 'react-ga/version-bower.js' {
  declare module.exports: $Exports<'react-ga/version-bower'>;
}
