// flow-typed signature: a3da118b64af32098e2208b9cd3e51ce
// flow-typed version: <<STUB>>/react-cookie_v^2.1.1/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cookie' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cookie/lib/Cookies' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/CookiesProvider' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/index' {
  declare module.exports: any;
}

declare module 'react-cookie/lib/withCookies' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cookie/lib/Cookies.js' {
  declare module.exports: $Exports<'react-cookie/lib/Cookies'>;
}
declare module 'react-cookie/lib/CookiesProvider.js' {
  declare module.exports: $Exports<'react-cookie/lib/CookiesProvider'>;
}
declare module 'react-cookie/lib/index.js' {
  declare module.exports: $Exports<'react-cookie/lib/index'>;
}
declare module 'react-cookie/lib/withCookies.js' {
  declare module.exports: $Exports<'react-cookie/lib/withCookies'>;
}
