// flow-typed signature: adf105beb9d5e6ce9282c5fb2f17397d
// flow-typed version: <<STUB>>/react-native-web_v^0.1.7/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-web/babel/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Animated/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/AppContainer' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppRegistry/renderApplication' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AppState/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/AsyncStorage/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/BackHandler/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Clipboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Dimensions/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Easing/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/I18nManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/InteractionManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Keyboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Linking/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/NetInfo/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/PanResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/PixelRatio/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Platform/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/createReactDOMStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/flattenStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/generateCss' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/i18nStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/normalizeValue' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/registry' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/staticCss' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/StyleManager' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/StyleRegistry' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/StyleSheet/StyleSheetValidation' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/UIManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/apis/Vibration/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ActivityIndicator/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Button/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/FlatList/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/ImageResizeMode' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/ImageStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/ImageUriCache' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Image/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/KeyboardAvoidingView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/ListViewDataSource' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ListView/ListViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Modal/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Picker/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/RefreshControl/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ScrollView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/ScrollView/ScrollViewBase' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/SectionList/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Slider/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/StaticContainer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/StaticRenderer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/StatusBar/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Switch/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Text/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Text/TextPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Text/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/TextInput/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/TextInput/TextInputState' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/TextInput/TextInputStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/BoundingDimensions' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/ensureComponentIsNative' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/ensurePositiveDelayProps' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/Position' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/Touchable' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableNativeFeedback' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/Touchable/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/UnimplementedView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/View/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/View/ViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/View/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/components/VirtualizedList/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/module' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/AccessibilityUtil/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/AccessibilityUtil/isDisabled' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/AccessibilityUtil/propsToAccessibilityComponent' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/AccessibilityUtil/propsToAriaRole' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/AccessibilityUtil/propsToTabIndex' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/applyLayout/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/applyNativeMethods/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/AssetRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/createDOMProps/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/createElement/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/dismissKeyboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/findNodeHandle/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/flattenArray/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ImageLoader/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/injectResponderEventPlugin/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/mapKeyValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/modality/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/multiplyStyleLengthValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/NativeMethodsMixin/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/NativeModules/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/normalizeNativeEvent/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/prefixStyles/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/prefixStyles/static' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/processColor/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ReactNativePropRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/requestIdleCallback/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/ScrollResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/modules/unitlessNumbers/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/AnimationPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/BaseComponentPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/BorderPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/ColorPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/createStrictShapeTypeChecker' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/EdgeInsetsPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/LayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/PointPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/ShadowPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/StyleSheetPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/propTypes/TransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/ReactNative' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/vendor/dangerousStyleValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/vendor/hash/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/vendor/PooledClass/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/vendor/setValueForStyles/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/vendor/TouchHistoryMath/index' {
  declare module.exports: any;
}

declare module 'react-native-web/dist/vendor/warnValidStyle/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Animated/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppRegistry/AppContainer' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppRegistry/renderApplication' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AppState/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/AsyncStorage/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/BackHandler/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Clipboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Dimensions/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Easing/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/I18nManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/InteractionManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Keyboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Linking/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/NetInfo/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/PanResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/PixelRatio/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Platform/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/createReactDOMStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/flattenStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/generateCss' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/i18nStyle' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/normalizeValue' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/registry' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/staticCss' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/StyleManager' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/StyleRegistry' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/StyleSheet/StyleSheetValidation' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/UIManager/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/apis/Vibration/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ActivityIndicator/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Button/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/FlatList/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Image/ImageResizeMode' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Image/ImageStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Image/ImageUriCache' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Image/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/KeyboardAvoidingView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ListView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ListView/ListViewDataSource' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ListView/ListViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Modal/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Picker/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ProgressBar/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/RefreshControl/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ScrollView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/ScrollView/ScrollViewBase' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/SectionList/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Slider/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/StaticContainer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/StaticRenderer/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/StatusBar/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Switch/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Text/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Text/TextPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Text/TextStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/TextInput/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/TextInput/TextInputState' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/TextInput/TextInputStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/BoundingDimensions' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/ensureComponentIsNative' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/ensurePositiveDelayProps' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/Position' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/Touchable' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/TouchableHighlight' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/TouchableNativeFeedback' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/TouchableOpacity' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/Touchable/TouchableWithoutFeedback' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/UnimplementedView/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/View/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/View/ViewPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/View/ViewStylePropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/components/VirtualizedList/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/module' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/AccessibilityUtil/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/AccessibilityUtil/isDisabled' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/AccessibilityUtil/propsToAccessibilityComponent' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/AccessibilityUtil/propsToAriaRole' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/AccessibilityUtil/propsToTabIndex' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/applyLayout/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/applyNativeMethods/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/AssetRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/createDOMProps/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/createElement/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/dismissKeyboard/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/findNodeHandle/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/flattenArray/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/ImageLoader/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/injectResponderEventPlugin/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/mapKeyValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/modality/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/multiplyStyleLengthValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/NativeMethodsMixin/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/NativeModules/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/normalizeNativeEvent/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/prefixStyles/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/prefixStyles/static' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/processColor/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/ReactNativePropRegistry/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/requestIdleCallback/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/ScrollResponder/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/modules/unitlessNumbers/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/AnimationPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/BaseComponentPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/BorderPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/ColorPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/createStrictShapeTypeChecker' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/EdgeInsetsPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/LayoutPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/PointPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/ShadowPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/StyleSheetPropType' {
  declare module.exports: any;
}

declare module 'react-native-web/src/propTypes/TransformPropTypes' {
  declare module.exports: any;
}

declare module 'react-native-web/src/vendor/dangerousStyleValue/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/vendor/hash/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/vendor/PooledClass/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/vendor/setValueForStyles/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/vendor/TouchHistoryMath/index' {
  declare module.exports: any;
}

declare module 'react-native-web/src/vendor/warnValidStyle/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-web/babel/index.js' {
  declare module.exports: $Exports<'react-native-web/babel/index'>;
}
declare module 'react-native-web/dist/apis/Animated/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Animated/index'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/AppContainer.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/AppContainer'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/index'>;
}
declare module 'react-native-web/dist/apis/AppRegistry/renderApplication.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppRegistry/renderApplication'>;
}
declare module 'react-native-web/dist/apis/AppState/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AppState/index'>;
}
declare module 'react-native-web/dist/apis/AsyncStorage/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/AsyncStorage/index'>;
}
declare module 'react-native-web/dist/apis/BackHandler/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/BackHandler/index'>;
}
declare module 'react-native-web/dist/apis/Clipboard/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Clipboard/index'>;
}
declare module 'react-native-web/dist/apis/Dimensions/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Dimensions/index'>;
}
declare module 'react-native-web/dist/apis/Easing/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Easing/index'>;
}
declare module 'react-native-web/dist/apis/I18nManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/I18nManager/index'>;
}
declare module 'react-native-web/dist/apis/InteractionManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/InteractionManager/index'>;
}
declare module 'react-native-web/dist/apis/Keyboard/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Keyboard/index'>;
}
declare module 'react-native-web/dist/apis/Linking/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Linking/index'>;
}
declare module 'react-native-web/dist/apis/NetInfo/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/NetInfo/index'>;
}
declare module 'react-native-web/dist/apis/PanResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/PanResponder/index'>;
}
declare module 'react-native-web/dist/apis/PixelRatio/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/PixelRatio/index'>;
}
declare module 'react-native-web/dist/apis/Platform/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Platform/index'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/createReactDOMStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/createReactDOMStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/flattenStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/flattenStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/generateCss.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/generateCss'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/i18nStyle.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/i18nStyle'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/index'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/normalizeValue.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/normalizeValue'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/registry.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/registry'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/staticCss.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/staticCss'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/StyleManager.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/StyleManager'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/StyleRegistry.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/StyleRegistry'>;
}
declare module 'react-native-web/dist/apis/StyleSheet/StyleSheetValidation.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/StyleSheet/StyleSheetValidation'>;
}
declare module 'react-native-web/dist/apis/UIManager/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/UIManager/index'>;
}
declare module 'react-native-web/dist/apis/Vibration/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/apis/Vibration/index'>;
}
declare module 'react-native-web/dist/components/ActivityIndicator/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ActivityIndicator/index'>;
}
declare module 'react-native-web/dist/components/Button/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Button/index'>;
}
declare module 'react-native-web/dist/components/FlatList/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/FlatList/index'>;
}
declare module 'react-native-web/dist/components/Image/ImageResizeMode.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/ImageResizeMode'>;
}
declare module 'react-native-web/dist/components/Image/ImageStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/ImageStylePropTypes'>;
}
declare module 'react-native-web/dist/components/Image/ImageUriCache.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/ImageUriCache'>;
}
declare module 'react-native-web/dist/components/Image/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Image/index'>;
}
declare module 'react-native-web/dist/components/KeyboardAvoidingView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/KeyboardAvoidingView/index'>;
}
declare module 'react-native-web/dist/components/ListView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/index'>;
}
declare module 'react-native-web/dist/components/ListView/ListViewDataSource.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/ListViewDataSource'>;
}
declare module 'react-native-web/dist/components/ListView/ListViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ListView/ListViewPropTypes'>;
}
declare module 'react-native-web/dist/components/Modal/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Modal/index'>;
}
declare module 'react-native-web/dist/components/Picker/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Picker/index'>;
}
declare module 'react-native-web/dist/components/ProgressBar/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ProgressBar/index'>;
}
declare module 'react-native-web/dist/components/RefreshControl/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/RefreshControl/index'>;
}
declare module 'react-native-web/dist/components/ScrollView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ScrollView/index'>;
}
declare module 'react-native-web/dist/components/ScrollView/ScrollViewBase.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/ScrollView/ScrollViewBase'>;
}
declare module 'react-native-web/dist/components/SectionList/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/SectionList/index'>;
}
declare module 'react-native-web/dist/components/Slider/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Slider/index'>;
}
declare module 'react-native-web/dist/components/StaticContainer/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/StaticContainer/index'>;
}
declare module 'react-native-web/dist/components/StaticRenderer/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/StaticRenderer/index'>;
}
declare module 'react-native-web/dist/components/StatusBar/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/StatusBar/index'>;
}
declare module 'react-native-web/dist/components/Switch/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Switch/index'>;
}
declare module 'react-native-web/dist/components/Text/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Text/index'>;
}
declare module 'react-native-web/dist/components/Text/TextPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Text/TextPropTypes'>;
}
declare module 'react-native-web/dist/components/Text/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Text/TextStylePropTypes'>;
}
declare module 'react-native-web/dist/components/TextInput/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/TextInput/index'>;
}
declare module 'react-native-web/dist/components/TextInput/TextInputState.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/TextInput/TextInputState'>;
}
declare module 'react-native-web/dist/components/TextInput/TextInputStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/TextInput/TextInputStylePropTypes'>;
}
declare module 'react-native-web/dist/components/Touchable/BoundingDimensions.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/BoundingDimensions'>;
}
declare module 'react-native-web/dist/components/Touchable/ensureComponentIsNative.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/ensureComponentIsNative'>;
}
declare module 'react-native-web/dist/components/Touchable/ensurePositiveDelayProps.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/ensurePositiveDelayProps'>;
}
declare module 'react-native-web/dist/components/Touchable/Position.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/Position'>;
}
declare module 'react-native-web/dist/components/Touchable/Touchable.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/Touchable'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableHighlight'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableNativeFeedback.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableNativeFeedback'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableOpacity'>;
}
declare module 'react-native-web/dist/components/Touchable/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/Touchable/TouchableWithoutFeedback'>;
}
declare module 'react-native-web/dist/components/UnimplementedView/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/UnimplementedView/index'>;
}
declare module 'react-native-web/dist/components/View/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/View/index'>;
}
declare module 'react-native-web/dist/components/View/ViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/View/ViewPropTypes'>;
}
declare module 'react-native-web/dist/components/View/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/View/ViewStylePropTypes'>;
}
declare module 'react-native-web/dist/components/VirtualizedList/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/components/VirtualizedList/index'>;
}
declare module 'react-native-web/dist/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/index'>;
}
declare module 'react-native-web/dist/module.js' {
  declare module.exports: $Exports<'react-native-web/dist/module'>;
}
declare module 'react-native-web/dist/modules/AccessibilityUtil/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/AccessibilityUtil/index'>;
}
declare module 'react-native-web/dist/modules/AccessibilityUtil/isDisabled.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/AccessibilityUtil/isDisabled'>;
}
declare module 'react-native-web/dist/modules/AccessibilityUtil/propsToAccessibilityComponent.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/AccessibilityUtil/propsToAccessibilityComponent'>;
}
declare module 'react-native-web/dist/modules/AccessibilityUtil/propsToAriaRole.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/AccessibilityUtil/propsToAriaRole'>;
}
declare module 'react-native-web/dist/modules/AccessibilityUtil/propsToTabIndex.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/AccessibilityUtil/propsToTabIndex'>;
}
declare module 'react-native-web/dist/modules/applyLayout/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/applyLayout/index'>;
}
declare module 'react-native-web/dist/modules/applyNativeMethods/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/applyNativeMethods/index'>;
}
declare module 'react-native-web/dist/modules/AssetRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/AssetRegistry/index'>;
}
declare module 'react-native-web/dist/modules/createDOMProps/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/createDOMProps/index'>;
}
declare module 'react-native-web/dist/modules/createElement/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/createElement/index'>;
}
declare module 'react-native-web/dist/modules/dismissKeyboard/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/dismissKeyboard/index'>;
}
declare module 'react-native-web/dist/modules/findNodeHandle/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/findNodeHandle/index'>;
}
declare module 'react-native-web/dist/modules/flattenArray/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/flattenArray/index'>;
}
declare module 'react-native-web/dist/modules/ImageLoader/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ImageLoader/index'>;
}
declare module 'react-native-web/dist/modules/injectResponderEventPlugin/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/injectResponderEventPlugin/index'>;
}
declare module 'react-native-web/dist/modules/mapKeyValue/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/mapKeyValue/index'>;
}
declare module 'react-native-web/dist/modules/modality/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/modality/index'>;
}
declare module 'react-native-web/dist/modules/multiplyStyleLengthValue/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/multiplyStyleLengthValue/index'>;
}
declare module 'react-native-web/dist/modules/NativeMethodsMixin/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/NativeMethodsMixin/index'>;
}
declare module 'react-native-web/dist/modules/NativeModules/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/NativeModules/index'>;
}
declare module 'react-native-web/dist/modules/normalizeNativeEvent/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/normalizeNativeEvent/index'>;
}
declare module 'react-native-web/dist/modules/prefixStyles/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/prefixStyles/index'>;
}
declare module 'react-native-web/dist/modules/prefixStyles/static.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/prefixStyles/static'>;
}
declare module 'react-native-web/dist/modules/processColor/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/processColor/index'>;
}
declare module 'react-native-web/dist/modules/ReactNativePropRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ReactNativePropRegistry/index'>;
}
declare module 'react-native-web/dist/modules/requestIdleCallback/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/requestIdleCallback/index'>;
}
declare module 'react-native-web/dist/modules/ScrollResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/ScrollResponder/index'>;
}
declare module 'react-native-web/dist/modules/unitlessNumbers/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/modules/unitlessNumbers/index'>;
}
declare module 'react-native-web/dist/propTypes/AnimationPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/AnimationPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/BaseComponentPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/BaseComponentPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/BorderPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/BorderPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/ColorPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/ColorPropType'>;
}
declare module 'react-native-web/dist/propTypes/createStrictShapeTypeChecker.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/createStrictShapeTypeChecker'>;
}
declare module 'react-native-web/dist/propTypes/EdgeInsetsPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/EdgeInsetsPropType'>;
}
declare module 'react-native-web/dist/propTypes/LayoutPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/LayoutPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/PointPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/PointPropType'>;
}
declare module 'react-native-web/dist/propTypes/ShadowPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/ShadowPropTypes'>;
}
declare module 'react-native-web/dist/propTypes/StyleSheetPropType.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/StyleSheetPropType'>;
}
declare module 'react-native-web/dist/propTypes/TransformPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/dist/propTypes/TransformPropTypes'>;
}
declare module 'react-native-web/dist/ReactNative.js' {
  declare module.exports: $Exports<'react-native-web/dist/ReactNative'>;
}
declare module 'react-native-web/dist/vendor/dangerousStyleValue/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/vendor/dangerousStyleValue/index'>;
}
declare module 'react-native-web/dist/vendor/hash/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/vendor/hash/index'>;
}
declare module 'react-native-web/dist/vendor/PooledClass/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/vendor/PooledClass/index'>;
}
declare module 'react-native-web/dist/vendor/setValueForStyles/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/vendor/setValueForStyles/index'>;
}
declare module 'react-native-web/dist/vendor/TouchHistoryMath/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/vendor/TouchHistoryMath/index'>;
}
declare module 'react-native-web/dist/vendor/warnValidStyle/index.js' {
  declare module.exports: $Exports<'react-native-web/dist/vendor/warnValidStyle/index'>;
}
declare module 'react-native-web/src/apis/Animated/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Animated/index'>;
}
declare module 'react-native-web/src/apis/AppRegistry/AppContainer.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppRegistry/AppContainer'>;
}
declare module 'react-native-web/src/apis/AppRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppRegistry/index'>;
}
declare module 'react-native-web/src/apis/AppRegistry/renderApplication.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppRegistry/renderApplication'>;
}
declare module 'react-native-web/src/apis/AppState/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AppState/index'>;
}
declare module 'react-native-web/src/apis/AsyncStorage/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/AsyncStorage/index'>;
}
declare module 'react-native-web/src/apis/BackHandler/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/BackHandler/index'>;
}
declare module 'react-native-web/src/apis/Clipboard/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Clipboard/index'>;
}
declare module 'react-native-web/src/apis/Dimensions/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Dimensions/index'>;
}
declare module 'react-native-web/src/apis/Easing/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Easing/index'>;
}
declare module 'react-native-web/src/apis/I18nManager/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/I18nManager/index'>;
}
declare module 'react-native-web/src/apis/InteractionManager/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/InteractionManager/index'>;
}
declare module 'react-native-web/src/apis/Keyboard/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Keyboard/index'>;
}
declare module 'react-native-web/src/apis/Linking/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Linking/index'>;
}
declare module 'react-native-web/src/apis/NetInfo/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/NetInfo/index'>;
}
declare module 'react-native-web/src/apis/PanResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/PanResponder/index'>;
}
declare module 'react-native-web/src/apis/PixelRatio/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/PixelRatio/index'>;
}
declare module 'react-native-web/src/apis/Platform/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Platform/index'>;
}
declare module 'react-native-web/src/apis/StyleSheet/createReactDOMStyle.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/createReactDOMStyle'>;
}
declare module 'react-native-web/src/apis/StyleSheet/flattenStyle.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/flattenStyle'>;
}
declare module 'react-native-web/src/apis/StyleSheet/generateCss.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/generateCss'>;
}
declare module 'react-native-web/src/apis/StyleSheet/i18nStyle.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/i18nStyle'>;
}
declare module 'react-native-web/src/apis/StyleSheet/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/index'>;
}
declare module 'react-native-web/src/apis/StyleSheet/normalizeValue.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/normalizeValue'>;
}
declare module 'react-native-web/src/apis/StyleSheet/registry.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/registry'>;
}
declare module 'react-native-web/src/apis/StyleSheet/staticCss.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/staticCss'>;
}
declare module 'react-native-web/src/apis/StyleSheet/StyleManager.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/StyleManager'>;
}
declare module 'react-native-web/src/apis/StyleSheet/StyleRegistry.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/StyleRegistry'>;
}
declare module 'react-native-web/src/apis/StyleSheet/StyleSheetValidation.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/StyleSheet/StyleSheetValidation'>;
}
declare module 'react-native-web/src/apis/UIManager/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/UIManager/index'>;
}
declare module 'react-native-web/src/apis/Vibration/index.js' {
  declare module.exports: $Exports<'react-native-web/src/apis/Vibration/index'>;
}
declare module 'react-native-web/src/components/ActivityIndicator/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ActivityIndicator/index'>;
}
declare module 'react-native-web/src/components/Button/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Button/index'>;
}
declare module 'react-native-web/src/components/FlatList/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/FlatList/index'>;
}
declare module 'react-native-web/src/components/Image/ImageResizeMode.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Image/ImageResizeMode'>;
}
declare module 'react-native-web/src/components/Image/ImageStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Image/ImageStylePropTypes'>;
}
declare module 'react-native-web/src/components/Image/ImageUriCache.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Image/ImageUriCache'>;
}
declare module 'react-native-web/src/components/Image/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Image/index'>;
}
declare module 'react-native-web/src/components/KeyboardAvoidingView/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/KeyboardAvoidingView/index'>;
}
declare module 'react-native-web/src/components/ListView/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ListView/index'>;
}
declare module 'react-native-web/src/components/ListView/ListViewDataSource.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ListView/ListViewDataSource'>;
}
declare module 'react-native-web/src/components/ListView/ListViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ListView/ListViewPropTypes'>;
}
declare module 'react-native-web/src/components/Modal/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Modal/index'>;
}
declare module 'react-native-web/src/components/Picker/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Picker/index'>;
}
declare module 'react-native-web/src/components/ProgressBar/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ProgressBar/index'>;
}
declare module 'react-native-web/src/components/RefreshControl/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/RefreshControl/index'>;
}
declare module 'react-native-web/src/components/ScrollView/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ScrollView/index'>;
}
declare module 'react-native-web/src/components/ScrollView/ScrollViewBase.js' {
  declare module.exports: $Exports<'react-native-web/src/components/ScrollView/ScrollViewBase'>;
}
declare module 'react-native-web/src/components/SectionList/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/SectionList/index'>;
}
declare module 'react-native-web/src/components/Slider/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Slider/index'>;
}
declare module 'react-native-web/src/components/StaticContainer/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/StaticContainer/index'>;
}
declare module 'react-native-web/src/components/StaticRenderer/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/StaticRenderer/index'>;
}
declare module 'react-native-web/src/components/StatusBar/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/StatusBar/index'>;
}
declare module 'react-native-web/src/components/Switch/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Switch/index'>;
}
declare module 'react-native-web/src/components/Text/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Text/index'>;
}
declare module 'react-native-web/src/components/Text/TextPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Text/TextPropTypes'>;
}
declare module 'react-native-web/src/components/Text/TextStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Text/TextStylePropTypes'>;
}
declare module 'react-native-web/src/components/TextInput/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/TextInput/index'>;
}
declare module 'react-native-web/src/components/TextInput/TextInputState.js' {
  declare module.exports: $Exports<'react-native-web/src/components/TextInput/TextInputState'>;
}
declare module 'react-native-web/src/components/TextInput/TextInputStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/TextInput/TextInputStylePropTypes'>;
}
declare module 'react-native-web/src/components/Touchable/BoundingDimensions.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/BoundingDimensions'>;
}
declare module 'react-native-web/src/components/Touchable/ensureComponentIsNative.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/ensureComponentIsNative'>;
}
declare module 'react-native-web/src/components/Touchable/ensurePositiveDelayProps.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/ensurePositiveDelayProps'>;
}
declare module 'react-native-web/src/components/Touchable/Position.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/Position'>;
}
declare module 'react-native-web/src/components/Touchable/Touchable.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/Touchable'>;
}
declare module 'react-native-web/src/components/Touchable/TouchableHighlight.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/TouchableHighlight'>;
}
declare module 'react-native-web/src/components/Touchable/TouchableNativeFeedback.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/TouchableNativeFeedback'>;
}
declare module 'react-native-web/src/components/Touchable/TouchableOpacity.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/TouchableOpacity'>;
}
declare module 'react-native-web/src/components/Touchable/TouchableWithoutFeedback.js' {
  declare module.exports: $Exports<'react-native-web/src/components/Touchable/TouchableWithoutFeedback'>;
}
declare module 'react-native-web/src/components/UnimplementedView/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/UnimplementedView/index'>;
}
declare module 'react-native-web/src/components/View/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/View/index'>;
}
declare module 'react-native-web/src/components/View/ViewPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/View/ViewPropTypes'>;
}
declare module 'react-native-web/src/components/View/ViewStylePropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/components/View/ViewStylePropTypes'>;
}
declare module 'react-native-web/src/components/VirtualizedList/index.js' {
  declare module.exports: $Exports<'react-native-web/src/components/VirtualizedList/index'>;
}
declare module 'react-native-web/src/index.js' {
  declare module.exports: $Exports<'react-native-web/src/index'>;
}
declare module 'react-native-web/src/module.js' {
  declare module.exports: $Exports<'react-native-web/src/module'>;
}
declare module 'react-native-web/src/modules/AccessibilityUtil/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/AccessibilityUtil/index'>;
}
declare module 'react-native-web/src/modules/AccessibilityUtil/isDisabled.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/AccessibilityUtil/isDisabled'>;
}
declare module 'react-native-web/src/modules/AccessibilityUtil/propsToAccessibilityComponent.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/AccessibilityUtil/propsToAccessibilityComponent'>;
}
declare module 'react-native-web/src/modules/AccessibilityUtil/propsToAriaRole.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/AccessibilityUtil/propsToAriaRole'>;
}
declare module 'react-native-web/src/modules/AccessibilityUtil/propsToTabIndex.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/AccessibilityUtil/propsToTabIndex'>;
}
declare module 'react-native-web/src/modules/applyLayout/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/applyLayout/index'>;
}
declare module 'react-native-web/src/modules/applyNativeMethods/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/applyNativeMethods/index'>;
}
declare module 'react-native-web/src/modules/AssetRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/AssetRegistry/index'>;
}
declare module 'react-native-web/src/modules/createDOMProps/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/createDOMProps/index'>;
}
declare module 'react-native-web/src/modules/createElement/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/createElement/index'>;
}
declare module 'react-native-web/src/modules/dismissKeyboard/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/dismissKeyboard/index'>;
}
declare module 'react-native-web/src/modules/findNodeHandle/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/findNodeHandle/index'>;
}
declare module 'react-native-web/src/modules/flattenArray/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/flattenArray/index'>;
}
declare module 'react-native-web/src/modules/ImageLoader/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/ImageLoader/index'>;
}
declare module 'react-native-web/src/modules/injectResponderEventPlugin/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/injectResponderEventPlugin/index'>;
}
declare module 'react-native-web/src/modules/mapKeyValue/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/mapKeyValue/index'>;
}
declare module 'react-native-web/src/modules/modality/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/modality/index'>;
}
declare module 'react-native-web/src/modules/multiplyStyleLengthValue/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/multiplyStyleLengthValue/index'>;
}
declare module 'react-native-web/src/modules/NativeMethodsMixin/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/NativeMethodsMixin/index'>;
}
declare module 'react-native-web/src/modules/NativeModules/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/NativeModules/index'>;
}
declare module 'react-native-web/src/modules/normalizeNativeEvent/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/normalizeNativeEvent/index'>;
}
declare module 'react-native-web/src/modules/prefixStyles/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/prefixStyles/index'>;
}
declare module 'react-native-web/src/modules/prefixStyles/static.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/prefixStyles/static'>;
}
declare module 'react-native-web/src/modules/processColor/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/processColor/index'>;
}
declare module 'react-native-web/src/modules/ReactNativePropRegistry/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/ReactNativePropRegistry/index'>;
}
declare module 'react-native-web/src/modules/requestIdleCallback/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/requestIdleCallback/index'>;
}
declare module 'react-native-web/src/modules/ScrollResponder/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/ScrollResponder/index'>;
}
declare module 'react-native-web/src/modules/unitlessNumbers/index.js' {
  declare module.exports: $Exports<'react-native-web/src/modules/unitlessNumbers/index'>;
}
declare module 'react-native-web/src/propTypes/AnimationPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/AnimationPropTypes'>;
}
declare module 'react-native-web/src/propTypes/BaseComponentPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/BaseComponentPropTypes'>;
}
declare module 'react-native-web/src/propTypes/BorderPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/BorderPropTypes'>;
}
declare module 'react-native-web/src/propTypes/ColorPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/ColorPropType'>;
}
declare module 'react-native-web/src/propTypes/createStrictShapeTypeChecker.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/createStrictShapeTypeChecker'>;
}
declare module 'react-native-web/src/propTypes/EdgeInsetsPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/EdgeInsetsPropType'>;
}
declare module 'react-native-web/src/propTypes/LayoutPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/LayoutPropTypes'>;
}
declare module 'react-native-web/src/propTypes/PointPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/PointPropType'>;
}
declare module 'react-native-web/src/propTypes/ShadowPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/ShadowPropTypes'>;
}
declare module 'react-native-web/src/propTypes/StyleSheetPropType.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/StyleSheetPropType'>;
}
declare module 'react-native-web/src/propTypes/TransformPropTypes.js' {
  declare module.exports: $Exports<'react-native-web/src/propTypes/TransformPropTypes'>;
}
declare module 'react-native-web/src/vendor/dangerousStyleValue/index.js' {
  declare module.exports: $Exports<'react-native-web/src/vendor/dangerousStyleValue/index'>;
}
declare module 'react-native-web/src/vendor/hash/index.js' {
  declare module.exports: $Exports<'react-native-web/src/vendor/hash/index'>;
}
declare module 'react-native-web/src/vendor/PooledClass/index.js' {
  declare module.exports: $Exports<'react-native-web/src/vendor/PooledClass/index'>;
}
declare module 'react-native-web/src/vendor/setValueForStyles/index.js' {
  declare module.exports: $Exports<'react-native-web/src/vendor/setValueForStyles/index'>;
}
declare module 'react-native-web/src/vendor/TouchHistoryMath/index.js' {
  declare module.exports: $Exports<'react-native-web/src/vendor/TouchHistoryMath/index'>;
}
declare module 'react-native-web/src/vendor/warnValidStyle/index.js' {
  declare module.exports: $Exports<'react-native-web/src/vendor/warnValidStyle/index'>;
}
