// flow-typed signature: 31e9e6633a6014e77bafa862ebefe8a6
// flow-typed version: <<STUB>>/resolve-url-loader_v^2.1.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'resolve-url-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'resolve-url-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'resolve-url-loader/lib/find-file' {
  declare module.exports: any;
}

declare module 'resolve-url-loader/lib/sources-absolute-to-relative' {
  declare module.exports: any;
}

// Filename aliases
declare module 'resolve-url-loader/index' {
  declare module.exports: $Exports<'resolve-url-loader'>;
}
declare module 'resolve-url-loader/index.js' {
  declare module.exports: $Exports<'resolve-url-loader'>;
}
declare module 'resolve-url-loader/lib/find-file.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/find-file'>;
}
declare module 'resolve-url-loader/lib/sources-absolute-to-relative.js' {
  declare module.exports: $Exports<'resolve-url-loader/lib/sources-absolute-to-relative'>;
}
