// flow-typed signature: 12cca32ec38bb347a9d06fcf429683f3
// flow-typed version: <<STUB>>/source-list-map_v^2.0.0/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-list-map'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-list-map' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-list-map/lib/base64-vlq' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/CodeNode' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/fromStringWithSourceMap' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/helpers' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/index' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/MappingsContext' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/SingleLineNode' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/SourceListMap' {
  declare module.exports: any;
}

declare module 'source-list-map/lib/SourceNode' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-list-map/lib/base64-vlq.js' {
  declare module.exports: $Exports<'source-list-map/lib/base64-vlq'>;
}
declare module 'source-list-map/lib/CodeNode.js' {
  declare module.exports: $Exports<'source-list-map/lib/CodeNode'>;
}
declare module 'source-list-map/lib/fromStringWithSourceMap.js' {
  declare module.exports: $Exports<'source-list-map/lib/fromStringWithSourceMap'>;
}
declare module 'source-list-map/lib/helpers.js' {
  declare module.exports: $Exports<'source-list-map/lib/helpers'>;
}
declare module 'source-list-map/lib/index.js' {
  declare module.exports: $Exports<'source-list-map/lib/index'>;
}
declare module 'source-list-map/lib/MappingsContext.js' {
  declare module.exports: $Exports<'source-list-map/lib/MappingsContext'>;
}
declare module 'source-list-map/lib/SingleLineNode.js' {
  declare module.exports: $Exports<'source-list-map/lib/SingleLineNode'>;
}
declare module 'source-list-map/lib/SourceListMap.js' {
  declare module.exports: $Exports<'source-list-map/lib/SourceListMap'>;
}
declare module 'source-list-map/lib/SourceNode.js' {
  declare module.exports: $Exports<'source-list-map/lib/SourceNode'>;
}
