// flow-typed signature: 268a4dd7c0bde8851b04de73cb1cc27a
// flow-typed version: <<STUB>>/spinjs_v^0.2.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'spinjs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'spinjs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'spinjs/lib/Builder' {
  declare module.exports: any;
}

declare module 'spinjs/lib/ConfigPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/configRc' {
  declare module.exports: any;
}

declare module 'spinjs/lib/createConfig' {
  declare module.exports: any;
}

declare module 'spinjs/lib/executor' {
  declare module.exports: any;
}

declare module 'spinjs/lib/index' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/ApolloPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/CssProcessorPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/ES6Plugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/react-native/assetLoader' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/react-native/liveReloadMiddleware' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/react-native/react-native-polyfill' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/ReactNativePlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/ReactNativeWebPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/ReactPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/shared/JSRuleFinder' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/StyledComponentsPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/TCombPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/WebAssetsPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/plugins/WebpackPlugin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/requireModule' {
  declare module.exports: any;
}

declare module 'spinjs/lib/spin.config' {
  declare module.exports: any;
}

declare module 'spinjs/lib/Spin' {
  declare module.exports: any;
}

declare module 'spinjs/lib/Stack' {
  declare module.exports: any;
}

declare module 'spinjs/lib/webpack.config' {
  declare module.exports: any;
}

declare module 'spinjs/spin.config' {
  declare module.exports: any;
}

declare module 'spinjs/spin' {
  declare module.exports: any;
}

declare module 'spinjs/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'spinjs/lib/Builder.js' {
  declare module.exports: $Exports<'spinjs/lib/Builder'>;
}
declare module 'spinjs/lib/ConfigPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/ConfigPlugin'>;
}
declare module 'spinjs/lib/configRc.js' {
  declare module.exports: $Exports<'spinjs/lib/configRc'>;
}
declare module 'spinjs/lib/createConfig.js' {
  declare module.exports: $Exports<'spinjs/lib/createConfig'>;
}
declare module 'spinjs/lib/executor.js' {
  declare module.exports: $Exports<'spinjs/lib/executor'>;
}
declare module 'spinjs/lib/index.js' {
  declare module.exports: $Exports<'spinjs/lib/index'>;
}
declare module 'spinjs/lib/plugins/ApolloPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/ApolloPlugin'>;
}
declare module 'spinjs/lib/plugins/CssProcessorPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/CssProcessorPlugin'>;
}
declare module 'spinjs/lib/plugins/ES6Plugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/ES6Plugin'>;
}
declare module 'spinjs/lib/plugins/react-native/assetLoader.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/react-native/assetLoader'>;
}
declare module 'spinjs/lib/plugins/react-native/liveReloadMiddleware.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/react-native/liveReloadMiddleware'>;
}
declare module 'spinjs/lib/plugins/react-native/react-native-polyfill.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/react-native/react-native-polyfill'>;
}
declare module 'spinjs/lib/plugins/ReactNativePlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/ReactNativePlugin'>;
}
declare module 'spinjs/lib/plugins/ReactNativeWebPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/ReactNativeWebPlugin'>;
}
declare module 'spinjs/lib/plugins/ReactPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/ReactPlugin'>;
}
declare module 'spinjs/lib/plugins/shared/JSRuleFinder.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/shared/JSRuleFinder'>;
}
declare module 'spinjs/lib/plugins/StyledComponentsPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/StyledComponentsPlugin'>;
}
declare module 'spinjs/lib/plugins/TCombPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/TCombPlugin'>;
}
declare module 'spinjs/lib/plugins/WebAssetsPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/WebAssetsPlugin'>;
}
declare module 'spinjs/lib/plugins/WebpackPlugin.js' {
  declare module.exports: $Exports<'spinjs/lib/plugins/WebpackPlugin'>;
}
declare module 'spinjs/lib/requireModule.js' {
  declare module.exports: $Exports<'spinjs/lib/requireModule'>;
}
declare module 'spinjs/lib/spin.config.js' {
  declare module.exports: $Exports<'spinjs/lib/spin.config'>;
}
declare module 'spinjs/lib/Spin.js' {
  declare module.exports: $Exports<'spinjs/lib/Spin'>;
}
declare module 'spinjs/lib/Stack.js' {
  declare module.exports: $Exports<'spinjs/lib/Stack'>;
}
declare module 'spinjs/lib/webpack.config.js' {
  declare module.exports: $Exports<'spinjs/lib/webpack.config'>;
}
declare module 'spinjs/spin.config.js' {
  declare module.exports: $Exports<'spinjs/spin.config'>;
}
declare module 'spinjs/spin.js' {
  declare module.exports: $Exports<'spinjs/spin'>;
}
declare module 'spinjs/webpack.config.js' {
  declare module.exports: $Exports<'spinjs/webpack.config'>;
}
