// flow-typed signature: 4b9dcfd751f23f133d63d0c0f43abfb6
// flow-typed version: <<STUB>>/subscriptions-transport-ws_v^0.9.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'subscriptions-transport-ws'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'subscriptions-transport-ws' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'subscriptions-transport-ws/browser/client' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/client' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/defaults' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/index' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/legacy/parse-legacy-protocol' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/message-types' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/protocol' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/server' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/utils/empty-iterable' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/utils/is-subscriptions' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/utils/promise-to-iterable' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/dist/utils/rejection-iterable' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/scripts/post-install' {
  declare module.exports: any;
}

declare module 'subscriptions-transport-ws/unpkg-webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'subscriptions-transport-ws/browser/client.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/browser/client'>;
}
declare module 'subscriptions-transport-ws/dist/client.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/client'>;
}
declare module 'subscriptions-transport-ws/dist/defaults.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/defaults'>;
}
declare module 'subscriptions-transport-ws/dist/index.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/index'>;
}
declare module 'subscriptions-transport-ws/dist/legacy/parse-legacy-protocol.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/legacy/parse-legacy-protocol'>;
}
declare module 'subscriptions-transport-ws/dist/message-types.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/message-types'>;
}
declare module 'subscriptions-transport-ws/dist/protocol.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/protocol'>;
}
declare module 'subscriptions-transport-ws/dist/server.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/server'>;
}
declare module 'subscriptions-transport-ws/dist/utils/empty-iterable.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/utils/empty-iterable'>;
}
declare module 'subscriptions-transport-ws/dist/utils/is-subscriptions.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/utils/is-subscriptions'>;
}
declare module 'subscriptions-transport-ws/dist/utils/promise-to-iterable.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/utils/promise-to-iterable'>;
}
declare module 'subscriptions-transport-ws/dist/utils/rejection-iterable.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/dist/utils/rejection-iterable'>;
}
declare module 'subscriptions-transport-ws/scripts/post-install.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/scripts/post-install'>;
}
declare module 'subscriptions-transport-ws/unpkg-webpack.config.js' {
  declare module.exports: $Exports<'subscriptions-transport-ws/unpkg-webpack.config'>;
}
