// flow-typed signature: 94e9c74108732b7d196ce5bbdf8dcaa8
// flow-typed version: <<STUB>>/universal-cookie-express_v^2.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-cookie-express'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-cookie-express' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-cookie-express/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-cookie-express/lib/index.js' {
  declare module.exports: $Exports<'universal-cookie-express/lib/index'>;
}
