// flow-typed signature: 0524dacecc11bda5fdc82cde889d3c11
// flow-typed version: <<STUB>>/wait-on_v^2.0.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'wait-on'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'wait-on' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'wait-on/exampleConfig' {
  declare module.exports: any;
}

declare module 'wait-on/lib/wait-on' {
  declare module.exports: any;
}

declare module 'wait-on/test/api.mocha' {
  declare module.exports: any;
}

declare module 'wait-on/test/cli.mocha' {
  declare module.exports: any;
}

declare module 'wait-on/test/validation.mocha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'wait-on/exampleConfig.js' {
  declare module.exports: $Exports<'wait-on/exampleConfig'>;
}
declare module 'wait-on/lib/wait-on.js' {
  declare module.exports: $Exports<'wait-on/lib/wait-on'>;
}
declare module 'wait-on/test/api.mocha.js' {
  declare module.exports: $Exports<'wait-on/test/api.mocha'>;
}
declare module 'wait-on/test/cli.mocha.js' {
  declare module.exports: $Exports<'wait-on/test/cli.mocha'>;
}
declare module 'wait-on/test/validation.mocha.js' {
  declare module.exports: $Exports<'wait-on/test/validation.mocha'>;
}
