// flow-typed signature: afbf31e8c930d5ef7e5fea90dc4037a6
// flow-typed version: <<STUB>>/webpack-virtual-modules_v^0.1.8/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-virtual-modules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-virtual-modules' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-virtual-modules/virtual-stats' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-virtual-modules/index' {
  declare module.exports: $Exports<'webpack-virtual-modules'>;
}
declare module 'webpack-virtual-modules/index.js' {
  declare module.exports: $Exports<'webpack-virtual-modules'>;
}
declare module 'webpack-virtual-modules/virtual-stats.js' {
  declare module.exports: $Exports<'webpack-virtual-modules/virtual-stats'>;
}
